# Generated by Django 3.1.4 on 2021-01-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_procurementmethod'),
        ('users', '0002_add_users_mobile_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='master_data.governmentbody', verbose_name='निकाय'),
        ),
    ]
