# Generated by Django 3.1.4 on 2021-01-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_globalpermission'),
        ('users', '0003_add_users_body'),
    ]

    operations = [
    ]
