# Generated by Django 3.1.4 on 2020-12-28 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0008_actionplanactivity_allowancetype_committee_covidhospitalmanagementchecklistdescription_expenseheader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody')),
                ('create_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                       related_name='forms_fre_fy_from', to='master_data.fiscalyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAllowanceLine',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('bearer_num', models.IntegerField()),
                ('expense_amount', models.DecimalField(
                    decimal_places=2, max_digits=19)),
                ('remarks', models.DecimalField(decimal_places=2, max_digits=19)),
                ('allowance_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='master_data.allowancetype')),
                ('body', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody')),
                ('office_bearer', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='master_data.officebearer')),
                ('risk_allowance_line', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='forms.riskallowance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
