# Generated by Django 3.1.4 on 2020-12-28 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0007_model_company_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_medExp_gov', to='master_data.governmentbody')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_medExp_fy', to='master_data.fiscalyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalExpenseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('amt_agreement', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date_to_import', models.CharField(default='01/01/2000', max_length=15, verbose_name='आयात गर्ने मिति')),
                ('date_imported', models.CharField(default='01/01/2000', max_length=15, verbose_name='आयात मिति')),
                ('amt_imported', models.DecimalField(decimal_places=2, max_digits=19)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.medicalexpense')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='master_data.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
