# Generated by Django 3.1.4 on 2021-01-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidHospitalEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHospitalEquipmentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_required', models.IntegerField(blank=True, null=True, verbose_name='आबश्यक')),
                ('available', models.IntegerField(blank=True, null=True, verbose_name='उपलब्ध')),
                ('num_still_required', models.IntegerField(blank=True, null=True, verbose_name='नपुग')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(blank=True, choices=[(0, 'fund_receipt_expense'), (1, 'risk_allowance'), (2, 'medical_expense'), (3, 'medical_receipt'), (4, 'medical_use'), (5, 'med_purchase_desc'), (6, 'pcr_test_compliance_detail'), (7, 'pcr_lab_detail'), (8, 'rdt_test_detail'), (9, 'pcr_kit_usage')], default=1)),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('incomplete', 'INCOMPLETE'), ('submitted', 'SUBMITTED'), ('completed', 'COMPLETED')], default='started', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FundReceiptExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('fy_month_from', models.IntegerField(choices=[(1, 'वैशाख'), (2, 'जेष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'आश्विन'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फाल्गुण'), (12, 'चैत्र')], default=4, verbose_name='सुरु महिना')),
                ('fy_month_to', models.IntegerField(choices=[(1, 'वैशाख'), (2, 'जेष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'आश्विन'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फाल्गुण'), (12, 'चैत्र')], default=3, verbose_name='अन्त्य महिना')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundReceiptExpenseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('fy_start_received_amt', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='सुरुवात महिनासम्म प्राप्त रकम')),
                ('fy_end_received_amt', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='अन्त्य महिनासम्म प्राप्त रकम')),
                ('fy_start_expense_amt', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='सुरुवात महिनासम्म खर्च रकम')),
                ('fy_end_expense_amt', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='अन्त्य महिनासम्म खर्च रकम')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalExpenseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('amt_agreement', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date_to_import', models.CharField(default='01/01/2000', max_length=15, verbose_name='आपूर्ति गर्नुपर्ने मिति')),
                ('date_imported', models.CharField(default='01/01/2000', max_length=15, verbose_name='आपूर्ति गरेको मिति')),
                ('amt_imported', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='आपूर्ति भएको सामानको मुल्य')),
                ('remarks', models.CharField(blank=True, max_length=50, null=True, verbose_name='कैफियत')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalPurchaseDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalPurchaseDescriptionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('product_specificaiton', models.CharField(blank=True, max_length=255, null=True, verbose_name='सामानको छोटो स्पेशिफिकेशन')),
                ('date_procure_agreement', models.CharField(default='01/01/2000', max_length=15, verbose_name='खरिद सम्झौता मिति')),
                ('date_received', models.CharField(default='01/01/2000', max_length=15, verbose_name='सामान प्राप्त मिति')),
                ('qty', models.FloatField(blank=True, null=True, verbose_name='परीमाण')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='दर')),
                ('total_amt', models.FloatField(blank=True, null=True, verbose_name='कुल रकम')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalReceiptLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('quantity', models.IntegerField(verbose_name='परिमाण')),
                ('cost_received_items', models.FloatField(verbose_name='प्राप्त औषधी स्वास्थ्य सामग्री उपकरणको मूल्य')),
                ('usage_situation', models.CharField(max_length=300, verbose_name='प्रयोगको अवस्था')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalUseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='खरीद गरिएको ?')),
                ('product_price', models.FloatField(verbose_name='सामानको मुल्य')),
                ('unused_qty', models.IntegerField(verbose_name='प्रयोगमा नआएको परिमाण')),
                ('unused_reason', models.CharField(max_length=300, verbose_name='प्रयोगमा नआएको कारण')),
                ('remarks', models.CharField(max_length=300, verbose_name='कैफियत')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrKitUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrKitUsageLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_kit_received', models.IntegerField(blank=True, null=True, verbose_name='२०७६ चैत्र देखि २०७७ आषाढ सम्म पिसीआर किट प्राप्ती')),
                ('num_kit_expensed', models.IntegerField(blank=True, null=True, verbose_name='२०७७ आषाढमसान्त सम्म पीसिआर किट खर्च')),
                ('num_kit_available', models.IntegerField(blank=True, null=True, verbose_name='२०७७ आषाढमसान्त मौजदात किट')),
                ('num_tests', models.IntegerField(blank=True, null=True, verbose_name='परीक्षण संख्या')),
                ('num_wasted', models.IntegerField(blank=True, null=True, verbose_name='वेष्टेज गएको किट संख्या')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrLaboratoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrLaboratoryDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_tested_fy_end', models.IntegerField(blank=True, null=True, verbose_name='आषाढ मसान्तसम्म परीक्षण गरेको कुल संख्या')),
                ('num_infected', models.IntegerField(blank=True, null=True, verbose_name='परीक्षण मध्ये संक्रमितको संख्या')),
                ('time_test_result', models.FloatField(blank=True, null=True, verbose_name='दनतिजा दिन लाग्ने औषत समय')),
                ('expense_pcr_test', models.FloatField(blank=True, null=True, verbose_name='पीसीआर परीक्षणमा आषाढ समान्त सम्म भएको खर्च')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrTestComplianceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrTestComplianceDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('month', models.IntegerField(blank=True, choices=[(1, 'वैशाख'), (2, 'जेष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'आश्विन'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फाल्गुण'), (12, 'चैत्र')], null=True, verbose_name='महिना')),
                ('year', models.IntegerField(verbose_name='बर्ष:')),
                ('all_area_test_num', models.IntegerField(verbose_name='सबै क्षेत्रमा गरेको कुल परीक्षण संख्या')),
                ('all_area_infected_num', models.IntegerField(verbose_name='सबै क्षेत्रमा गरेको कुल  संक्रमित संख्या')),
                ('priority_1_test_num', models.IntegerField(verbose_name='Priority-1क्षेत्रमा गरेको परीक्षण संख्या')),
                ('priority_1_infected_num', models.IntegerField(verbose_name='Priority-1 क्षेत्रमा गरेको संक्रमित संख्या')),
                ('priority_2_test_num', models.IntegerField(verbose_name='Priority-2 क्षेत्रमा गरेको परीक्षण संख्या')),
                ('priority_2_infected_num', models.IntegerField(verbose_name='Priority-2 क्षेत्रमा गरेको संक्रमित संख्या')),
                ('priority_3_test_num', models.IntegerField(verbose_name='Priority-3 क्षेत्रमा गरेको परीक्षण संख्या')),
                ('priority_3_infected_num', models.IntegerField(verbose_name='Priority-3 क्षेत्रमा गरेको संक्रमित संख्या')),
                ('non_priority_test_num', models.IntegerField(verbose_name='Non-priority  क्षेत्रमा गरेको परीक्षण संख्या')),
                ('non_priority_infected_num', models.IntegerField(verbose_name='Non-priority  क्षेत्रमा गरेको संक्रमित संख्या')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RdtTestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RdtTestDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_tested_fy_end', models.IntegerField(verbose_name='आषाढ मसान्तसम्म आरडीटी परीक्षण गरेको संख्या')),
                ('num_tested_pcr', models.IntegerField(verbose_name='परीक्षण मध्ये पिसीआर गरिएको संख्या')),
                ('expense_rdt_test', models.IntegerField(verbose_name='आरडीटी परीक्षणमा आषाढ समान्त सम्म भएको खर्च')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAllowanceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('bearer_num', models.IntegerField(verbose_name='कर्मचारी वा पदाधिकारी संख्या')),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='खर्च रकम')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='कैफियत')),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.allowancetype', verbose_name='भत्ताको प्रकार')),
                ('gov_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='खर्च गर्ने निकायको नाम')),
                ('office_bearer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.officebearer', verbose_name='जोखिम भत्ता पाउने पदाधिकारी')),
                ('risk_allowance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.riskallowance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
