# Generated by Django 3.1.4 on 2021-01-26 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import master_data.models.fiscal_year


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidHospitalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covid_hospital_details', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covid_hospital_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHospitalEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('cov_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_cov_hos', to='master_data.covidhospital')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHospitalManagementChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.covidhospital', verbose_name='अस्पतालको नामः: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHospitalManpower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('covidhospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.covidhospital', verbose_name='कोभिड डेडिकेटेड अस्पातालको नाम:: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundReceiptExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('fy_month_from', models.IntegerField(choices=[(1, 'वैशाख'), (2, 'जेष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'आश्विन'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फाल्गुण'), (12, 'चैत्र')], default=4, verbose_name='सुरु महिना')),
                ('fy_month_to', models.IntegerField(choices=[(1, 'वैशाख'), (2, 'जेष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'आश्विन'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फाल्गुण'), (12, 'चैत्र')], default=3, verbose_name='अन्त्य महिना')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नाम')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_receipt_expenses', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष')),
                ('fiscal_year_from', models.ForeignKey(default=master_data.models.fiscal_year.get_current_fy, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fre_fy_from', to='master_data.fiscalyear', verbose_name='सुरु आर्थिक वर्ष')),
                ('fiscal_year_to', models.ForeignKey(default=master_data.models.fiscal_year.get_current_fy, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fre_fy_to', to='master_data.fiscalyear', verbose_name='अन्त्य आर्थिक वर्ष')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IsolationConstructionExependiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iso_centerexpentiture', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iso_cenexpentiture_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IsolationManagementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iso_management_body', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iso_management_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_medExp_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_medExp_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalPurchaseDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_medPurchase_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_medPurchase_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नाम')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_receipt', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_use', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrKitUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_pcrKit_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_pcrKit_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrLaboratoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_pcr_lab_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_pcr_lab_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrTestComplianceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pctr_test_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuarantineConstructionExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_quarantine_expense_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_quarantine_expense_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuarantineManagementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_quarantine_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_quarantine_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RdtTestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdt_test_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_fre_fy_from', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAllowanceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('bearer_num', models.IntegerField(verbose_name='कर्मचारी वा पदाधिकारी संख्या')),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='खर्च रकम')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='कैफियत')),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.allowancetype', verbose_name='भत्ताको प्रकार')),
                ('gov_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='खर्च गर्ने निकायको नाम')),
                ('office_bearer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.officebearer', verbose_name='जोखिम भत्ता पाउने पदाधिकारी')),
                ('risk_allowance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.riskallowance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RdtTestDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_tested_fy_end', models.IntegerField(verbose_name='आषाढ मसान्तसम्म आरडीटी परीक्षण गरेको संख्या')),
                ('num_tested_pcr', models.IntegerField(verbose_name='परीक्षण मध्ये पिसीआर गरिएको संख्या')),
                ('expense_rdt_test', models.IntegerField(verbose_name='आरडीटी परीक्षणमा आषाढ समान्त सम्म भएको खर्च')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.laboratory', verbose_name='ल्यावको नाम र स्थान')),
                ('rdt_test_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.rdttestdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuarantineManagementDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('cost_construction', models.FloatField(verbose_name='निर्माण खर्च')),
                ('num_bed', models.IntegerField(verbose_name='बेड संख्या')),
                ('max_num_daily_stay', models.IntegerField(verbose_name='दैनिकरुपमा बसेको अधिकतम\xa0 संख्या')),
                ('num_stayed_till_fy_end', models.IntegerField(verbose_name='आषाढ मसान्त सम्म क्वारेन्टिनमा बसेकाहरुको कुल संख्या')),
                ('expense_operations', models.FloatField(verbose_name='सञ्चालन ब्यबस्थापन प्रयोजनको खर्च')),
                ('isolation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolation_center', to='master_data.isolationcenter', verbose_name='यस निकायले तयार वा सञ्चालन गरेको क्वारेन्टिन/होल्डिङ सेन्टरको नाम')),
                ('quarantine_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.quarantinemanagementdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuarantineConstructionExpenditureLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('number', models.FloatField(verbose_name='संख्या')),
                ('unit_cost', models.FloatField(verbose_name='प्रति ईकाइ दर')),
                ('amt_expense', models.FloatField(verbose_name='खर्च रकम')),
                ('remarks', models.CharField(blank=True, max_length=50, null=True, verbose_name='कैफियत')),
                ('procure_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_procure', to='master_data.procurementmethod', verbose_name='खरिद विधि')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_product', to='master_data.product', verbose_name='खरिद भएका सामग्री')),
                ('quarantine_construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.quarantineconstructionexpenditure')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_uom', to='master_data.unitofmeasure', verbose_name='इकाई')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrTestComplianceDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('month', models.IntegerField(blank=True, choices=[(1, 'वैशाख'), (2, 'जेष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'आश्विन'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फाल्गुण'), (12, 'चैत्र')], null=True, verbose_name='महिना')),
                ('year', models.IntegerField(verbose_name='बर्ष:')),
                ('all_area_test_num', models.IntegerField(verbose_name='सबै क्षेत्रमा गरेको कुल परीक्षण संख्या')),
                ('all_area_infected_num', models.IntegerField(verbose_name='सबै क्षेत्रमा गरेको कुल  संक्रमित संख्या')),
                ('priority_1_test_num', models.IntegerField(verbose_name='Priority-1क्षेत्रमा गरेको परीक्षण संख्या')),
                ('priority_1_infected_num', models.IntegerField(verbose_name='Priority-1 क्षेत्रमा गरेको संक्रमित संख्या')),
                ('priority_2_test_num', models.IntegerField(verbose_name='Priority-2 क्षेत्रमा गरेको परीक्षण संख्या')),
                ('priority_2_infected_num', models.IntegerField(verbose_name='Priority-2 क्षेत्रमा गरेको संक्रमित संख्या')),
                ('priority_3_test_num', models.IntegerField(verbose_name='Priority-3 क्षेत्रमा गरेको परीक्षण संख्या')),
                ('priority_3_infected_num', models.IntegerField(verbose_name='Priority-3 क्षेत्रमा गरेको संक्रमित संख्या')),
                ('non_priority_test_num', models.IntegerField(verbose_name='Non-priority  क्षेत्रमा गरेको परीक्षण संख्या')),
                ('non_priority_infected_num', models.IntegerField(verbose_name='Non-priority  क्षेत्रमा गरेको संक्रमित संख्या')),
                ('pcrtest_compliance_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.pcrtestcompliancedetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrLaboratoryDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_tested_fy_end', models.IntegerField(blank=True, null=True, verbose_name='आषाढ मसान्तसम्म परीक्षण गरेको कुल संख्या')),
                ('num_infected', models.IntegerField(blank=True, null=True, verbose_name='परीक्षण मध्ये संक्रमितको संख्या')),
                ('time_test_result', models.FloatField(blank=True, null=True, verbose_name='दनतिजा दिन लाग्ने औषत समय')),
                ('expense_pcr_test', models.FloatField(blank=True, null=True, verbose_name='पीसीआर परीक्षणमा आषाढ समान्त सम्म भएको खर्च')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.laboratory', verbose_name='पीसीआर ल्यावको नाम र स्थान')),
                ('pcr_lab_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.pcrlaboratorydetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrKitUsageLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_kit_received', models.IntegerField(blank=True, null=True, verbose_name='२०७६ चैत्र देखि २०७७ आषाढ सम्म पिसीआर किट प्राप्ती')),
                ('num_kit_expensed', models.IntegerField(blank=True, null=True, verbose_name='२०७७ आषाढमसान्त सम्म पीसिआर किट खर्च')),
                ('num_kit_available', models.IntegerField(blank=True, null=True, verbose_name='२०७७ आषाढमसान्त मौजदात किट')),
                ('num_tests', models.IntegerField(blank=True, null=True, verbose_name='परीक्षण संख्या')),
                ('num_wasted', models.IntegerField(blank=True, null=True, verbose_name='वेष्टेज गएको किट संख्या')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.laboratory', verbose_name='प्रयोगशालाको नाम')),
                ('pcr_kit_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.pcrkitusage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalUseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='खरीद गरिएको ?')),
                ('product_price', models.FloatField(verbose_name='सामानको मुल्य')),
                ('unused_qty', models.IntegerField(verbose_name='प्रयोगमा नआएको परिमाण')),
                ('unused_reason', models.CharField(max_length=300, verbose_name='प्रयोगमा नआएको कारण')),
                ('remarks', models.CharField(max_length=300, verbose_name='कैफियत')),
                ('medical_use_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.medicaluse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.product', verbose_name='स्वास्थ्य सामाग्री उपकरणको विवरण')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalReceiptLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('quantity', models.IntegerField(verbose_name='परिमाण')),
                ('cost_received_items', models.FloatField(verbose_name='प्राप्त औषधी स्वास्थ्य सामग्री उपकरणको मूल्य')),
                ('usage_situation', models.CharField(max_length=300, verbose_name='प्रयोगको अवस्था')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('medical_receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.medicalreceipt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.product', verbose_name='स्वास्थ्य सामाग्री उपकरणको विवरण')),
                ('provider_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body_pro', to='master_data.governmentbody', verbose_name='प्रदान गर्ने निकाय')),
                ('provider_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_pro', to='master_data.institution', verbose_name='प्रदान गर्ने संस्था')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalPurchaseDescriptionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('product_specificaiton', models.CharField(blank=True, max_length=255, null=True, verbose_name='सामानको छोटो स्पेशिफिकेशन')),
                ('date_procure_agreement', models.CharField(default='01/01/2000', max_length=15, verbose_name='खरिद सम्झौता मिति')),
                ('date_received', models.CharField(default='01/01/2000', max_length=15, verbose_name='सामान प्राप्त मिति')),
                ('qty', models.FloatField(blank=True, null=True, verbose_name='परीमाण')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='दर')),
                ('total_amt', models.FloatField(blank=True, null=True, verbose_name='कुल रकम')),
                ('medical_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.medicalpurchasedescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.product', verbose_name='सामानको नाम')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.unitofmeasure', verbose_name='इकाई')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalExpenseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('amt_agreement', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date_to_import', models.CharField(default='01/01/2000', max_length=15, verbose_name='आपूर्ति गर्नुपर्ने मिति')),
                ('date_imported', models.CharField(default='01/01/2000', max_length=15, verbose_name='आपूर्ति गरेको मिति')),
                ('amt_imported', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='आपूर्ति भएको सामानको मुल्य')),
                ('remarks', models.CharField(blank=True, max_length=50, null=True, verbose_name='कैफियत')),
                ('medical_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.medicalexpense')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='master_data.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IsolationManagementDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('cost_construction', models.FloatField(verbose_name='निर्माण खर्च ')),
                ('num_bed', models.IntegerField(verbose_name='बेड संख्या')),
                ('max_num_daily_stay', models.IntegerField(verbose_name='आईसोलेशन केन्द्रमा बस्नेहरुको दैनिकरुपमा बसेको अधिकतम  संख्या')),
                ('num_stayed_till_fy_end', models.IntegerField(verbose_name='आईसोलेशन केन्द्रमा बस्नेहरुको आषाढ मसान्त सम्म आईसोलेशन केन्द्रमा बसेकाहरुको कुल संख्या')),
                ('expense_operations', models.FloatField(verbose_name='ब्यबस्थापन प्रयोजनको खर्च')),
                ('isolation_management_detail_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.isolationmanagementdetail')),
                ('isolationcenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.isolationcenter', verbose_name='यस निकायले तयार वा सञ्चालन गरेको आईसोलेशन केन्द्रको नाम')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IsolationConstructionExependitureLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('number', models.FloatField(verbose_name='संख्या')),
                ('unit_cost', models.FloatField(verbose_name='प्रति ईकाइ दर')),
                ('amt_expense', models.FloatField(verbose_name='खर्च रकम')),
                ('remarks', models.CharField(max_length=300, verbose_name='कैफियत')),
                ('isolation_cons_expentiture_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.isolationconstructionexependiture')),
                ('oum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasure', verbose_name='इकाई')),
                ('procure_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.procurementmethod', verbose_name='खरिद विधि')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.product', verbose_name='खरिद भएका सामग्री')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundReceiptExpenseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('fy_start_received_amt', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='सुरुवात महिनासम्म प्राप्त रकम')),
                ('fy_end_received_amt', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='अन्त्य महिनासम्म प्राप्त रकम')),
                ('fy_start_expense_amt', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='सुरुवात महिनासम्म खर्च रकम')),
                ('fy_end_expense_amt', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='अन्त्य महिनासम्म खर्च रकम')),
                ('budget_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.sourcebudget', verbose_name='बजेट/आम्दानीको स्रोत')),
                ('expense_header', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.expenseheader', verbose_name='खर्च शीर्षक')),
                ('receipt_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.fundreceiptexpense', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(blank=True, choices=[(0, 'fund_receipt_expense'), (1, 'risk_allowance'), (2, 'medical_expense'), (3, 'medical_receipt'), (4, 'medical_use'), (5, 'med_purchase_desc'), (6, 'pcr_test_compliance_detail'), (7, 'pcr_lab_detail'), (8, 'rdt_test_detail'), (9, 'pcr_kit_usage'), (10, 'covid_hos_mainpower'), (11, 'cov_hos_equipment'), (12, 'covid_hospital_detail'), (13, 'quarantine_management_detail'), (14, 'isolation_management_detail'), (15, 'quarantine_contruction_expenditure'), (16, 'isolation_construction_expenditure'), (17, 'cov_hos_management_checklist')], default=1)),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('incomplete', 'INCOMPLETE'), ('submitted', 'SUBMITTED'), ('completed', 'COMPLETED')], default='started', max_length=20)),
                ('cov_hos_equipment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitalequipment')),
                ('cov_hos_management_checklist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitalmanagementchecklist')),
                ('covid_hos_mainpower', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitalmanpower')),
                ('covid_hospital_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitaldetail')),
                ('fund_receipt_expense', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.fundreceiptexpense')),
                ('isolation_construction_expenditure', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.isolationconstructionexependiture')),
                ('isolation_management_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.isolationmanagementdetail')),
                ('med_purchase_desc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicalpurchasedescription')),
                ('medical_expense', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicalexpense')),
                ('medical_receipt', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicalreceipt')),
                ('medical_use', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicaluse')),
                ('pcr_kit_usage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.pcrkitusage')),
                ('pcr_lab_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.pcrlaboratorydetail')),
                ('pcr_test_compliance_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.pcrtestcompliancedetail')),
                ('quarantine_contruction_expenditure', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.quarantineconstructionexpenditure')),
                ('quarantine_management_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.quarantinemanagementdetail')),
                ('rdt_test_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.rdttestdetail')),
                ('risk_allowance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.riskallowance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CovidHospitalManpowerLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_required', models.IntegerField(verbose_name='दरबन्दी संख्या')),
                ('num_hired', models.IntegerField(verbose_name='पदपूर्ति संख्या')),
                ('num_vacant', models.IntegerField(verbose_name='रिक्त संख्या')),
                ('num_contract', models.IntegerField(verbose_name='पदपूर्ति मध्ये करार संख्या')),
                ('covidhospital_manpower_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.covidhospitalmanpower')),
                ('manpower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.manpower', verbose_name='स्वास्थ्य जनशक्ति')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHospitalManagementChecklistLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('is_yes', models.BooleanField(default=False, verbose_name='छ')),
                ('remarks', models.CharField(blank=True, max_length=50, null=True, verbose_name='कैफियत')),
                ('cov_hos_management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.covidhospitalmanagementchecklist')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.covidhospitalmanagementchecklistdescription', verbose_name='बिबरण')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHospitalEquipmentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_required', models.IntegerField(blank=True, null=True, verbose_name='आबश्यक')),
                ('available', models.IntegerField(blank=True, null=True, verbose_name='उपलब्ध')),
                ('num_still_required', models.IntegerField(blank=True, null=True, verbose_name='नपुग')),
                ('cov_hos_equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.covidhospitalequipment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.product', verbose_name='स्वास्थ्य उपकरण')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHospitalDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('announce_time_health_workers', models.IntegerField(verbose_name='कोभिड अस्पताल घोषणा हुँदाको अवस्थामा रहेको स्वास्थ्यकर्मीको संख्या')),
                ('announce_time_beds', models.IntegerField(verbose_name='कोभिड अस्पताल घोषणा हुँदाको अवस्थामा रहेको बेड संख्या')),
                ('announce_time_icu', models.IntegerField(verbose_name='कोभिड अस्पताल घोषणा हुँदाको अवस्थामा रहेको आई सी यु संख्या')),
                ('announce_time_ventilators', models.IntegerField(verbose_name='कोभिड अस्पताल घोषणा हुँदाको अवस्थामा रहेको भेन्टिलेटर संख्या')),
                ('added_health_workers', models.IntegerField(verbose_name='२०७७ असार मसान्तसम्म थप भएको स्वास्थ्यकर्मीको संख्या')),
                ('added_beds', models.IntegerField(verbose_name='२०७७ असार मसान्तसम्म थप भएको बेड संख्या')),
                ('added_icu', models.IntegerField(verbose_name='२०७७ असार मसान्तसम्म थप भएको आई सी यु संख्या')),
                ('added_ventilators', models.IntegerField(verbose_name='२०७७ असार मसान्तसम्म थप भएको भेन्टिलेटर संख्या')),
                ('num_treated_patients', models.IntegerField(verbose_name='२०७७ असार मसान्तसम्म उपचार गरेको कोभिड विरामी संख्या')),
                ('expense_treatment', models.FloatField(verbose_name='२०७७ असार मसान्तसम्म उपचारमा भएको खर्च')),
                ('covidhospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.covidhospital', verbose_name='डेडिकेटेड अस्पतालको नाम र स्थान')),
                ('covidhospital_hospital_detail_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.covidhospitaldetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
