# Generated by Django 3.1.4 on 2021-01-20 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskallowance',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskallowance',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_fre_fy_from', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: '),
        ),
        migrations.AddField(
            model_name='rdttestdetailline',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.laboratory', verbose_name='ल्यावको नाम र स्थान'),
        ),
        migrations.AddField(
            model_name='rdttestdetailline',
            name='rdt_test_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.rdttestdetail'),
        ),
        migrations.AddField(
            model_name='rdttestdetail',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: '),
        ),
        migrations.AddField(
            model_name='rdttestdetail',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rdttestdetail',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdt_test_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: '),
        ),
        migrations.AddField(
            model_name='pcrtestcompliancedetailline',
            name='pcrtest_compliance_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.pcrtestcompliancedetail'),
        ),
        migrations.AddField(
            model_name='pcrtestcompliancedetail',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: '),
        ),
        migrations.AddField(
            model_name='pcrtestcompliancedetail',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pcrtestcompliancedetail',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pctr_test_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: '),
        ),
        migrations.AddField(
            model_name='pcrlaboratorydetailline',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.laboratory', verbose_name='पीसीआर ल्यावको नाम र स्थान'),
        ),
        migrations.AddField(
            model_name='pcrlaboratorydetailline',
            name='pcr_lab_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.pcrlaboratorydetail'),
        ),
        migrations.AddField(
            model_name='pcrlaboratorydetail',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_pcr_lab_gov', to='master_data.governmentbody'),
        ),
        migrations.AddField(
            model_name='pcrlaboratorydetail',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pcrlaboratorydetail',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_pcr_lab_fy', to='master_data.fiscalyear'),
        ),
        migrations.AddField(
            model_name='pcrkitusageline',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.laboratory', verbose_name='प्रयोगशालाको नाम'),
        ),
        migrations.AddField(
            model_name='pcrkitusageline',
            name='pcr_kit_usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.pcrkitusage'),
        ),
        migrations.AddField(
            model_name='pcrkitusage',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_pcrKit_gov', to='master_data.governmentbody'),
        ),
        migrations.AddField(
            model_name='pcrkitusage',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pcrkitusage',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_pcrKit_fy', to='master_data.fiscalyear'),
        ),
        migrations.AddField(
            model_name='medicaluseline',
            name='medical_use_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.medicaluse'),
        ),
        migrations.AddField(
            model_name='medicaluseline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.product', verbose_name='स्वास्थ्य सामाग्री उपकरणको विवरण'),
        ),
        migrations.AddField(
            model_name='medicaluse',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: '),
        ),
        migrations.AddField(
            model_name='medicaluse',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaluse',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_use', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: '),
        ),
        migrations.AddField(
            model_name='medicalreceiptline',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalreceiptline',
            name='medical_receipt_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.medicalreceipt'),
        ),
        migrations.AddField(
            model_name='medicalreceiptline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.product', verbose_name='स्वास्थ्य सामाग्री उपकरणको विवरण'),
        ),
        migrations.AddField(
            model_name='medicalreceiptline',
            name='provider_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body_pro', to='master_data.governmentbody', verbose_name='प्रदान गर्ने निकाय'),
        ),
        migrations.AddField(
            model_name='medicalreceiptline',
            name='provider_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_pro', to='master_data.institution', verbose_name='प्रदान गर्ने संस्था'),
        ),
        migrations.AddField(
            model_name='medicalreceipt',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नाम'),
        ),
        migrations.AddField(
            model_name='medicalreceipt',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalreceipt',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_receipt', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष'),
        ),
        migrations.AddField(
            model_name='medicalpurchasedescriptionline',
            name='medical_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.medicalpurchasedescription'),
        ),
        migrations.AddField(
            model_name='medicalpurchasedescriptionline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.product', verbose_name='सामानको नाम'),
        ),
        migrations.AddField(
            model_name='medicalpurchasedescriptionline',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.unitofmeasure', verbose_name='इकाई'),
        ),
        migrations.AddField(
            model_name='medicalpurchasedescription',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_medPurchase_gov', to='master_data.governmentbody'),
        ),
        migrations.AddField(
            model_name='medicalpurchasedescription',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalpurchasedescription',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_medPurchase_fy', to='master_data.fiscalyear'),
        ),
        migrations.AddField(
            model_name='medicalexpenseline',
            name='medical_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.medicalexpense'),
        ),
        migrations.AddField(
            model_name='medicalexpenseline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='master_data.product'),
        ),
        migrations.AddField(
            model_name='medicalexpense',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_medExp_gov', to='master_data.governmentbody'),
        ),
        migrations.AddField(
            model_name='medicalexpense',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalexpense',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_medExp_fy', to='master_data.fiscalyear'),
        ),
        migrations.AddField(
            model_name='fundreceiptexpenseline',
            name='budget_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.sourcebudget', verbose_name='बजेट/आम्दानीको स्रोत'),
        ),
        migrations.AddField(
            model_name='fundreceiptexpenseline',
            name='expense_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.expenseheader', verbose_name='खर्च शीर्षक'),
        ),
        migrations.AddField(
            model_name='fundreceiptexpenseline',
            name='receipt_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.fundreceiptexpense', verbose_name=''),
        ),
        migrations.AddField(
            model_name='fundreceiptexpense',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नाम'),
        ),
        migrations.AddField(
            model_name='fundreceiptexpense',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundreceiptexpense',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_receipt_expenses', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष'),
        ),
        migrations.AddField(
            model_name='fundreceiptexpense',
            name='fiscal_year_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fre_fy_from', to='master_data.fiscalyear', verbose_name='सुरु आर्थिक वर्ष'),
        ),
        migrations.AddField(
            model_name='fundreceiptexpense',
            name='fiscal_year_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fre_fy_to', to='master_data.fiscalyear', verbose_name='अन्त्य आर्थिक वर्ष'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='fund_receipt_expense',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.fundreceiptexpense'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='med_purchase_desc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicalpurchasedescription'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='medical_expense',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicalexpense'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='medical_receipt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicalreceipt'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='medical_use',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicaluse'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='pcr_kit_usage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.pcrkitusage'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='pcr_lab_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.pcrlaboratorydetail'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='pcr_test_compliance_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.pcrtestcompliancedetail'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='rdt_test_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.rdttestdetail'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='risk_allowance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.riskallowance'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='covidhospitalequipmentline',
            name='cov_hos_equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.covidhospitalequipment'),
        ),
        migrations.AddField(
            model_name='covidhospitalequipmentline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.product', verbose_name='स्वास्थ्य उपकरण'),
        ),
        migrations.AddField(
            model_name='covidhospitalequipment',
            name='cov_hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_cov_hos', to='master_data.covidhospital'),
        ),
        migrations.AddField(
            model_name='covidhospitalequipment',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
