# Generated by Django 3.1.4 on 2020-12-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_add_medical_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexpenseline',
            name='amt_imported',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='आपूर्ति भएको सामानको मुल्य'),
        ),
        migrations.AlterField(
            model_name='medicalexpenseline',
            name='date_imported',
            field=models.CharField(default='01/01/2000', max_length=15, verbose_name='आपूर्ति गरेको मिति'),
        ),
        migrations.AlterField(
            model_name='medicalexpenseline',
            name='date_to_import',
            field=models.CharField(default='01/01/2000', max_length=15, verbose_name='आपूर्ति गर्नुपर्ने मिति'),
        ),
        migrations.AlterField(
            model_name='medicalexpenseline',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='कैफियत'),
        ),
    ]
