# Generated by Django 3.1.4 on 2020-12-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_actionplanactivity_allowancetype_committee_covidhospitalmanagementchecklistdescription_expenseheader'),
        ('forms', '0001_model_risk_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskallowance',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: '),
        ),
        migrations.AlterField(
            model_name='riskallowance',
            name='fiscal_year_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_fre_fy_from', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: '),
        ),
        migrations.AlterField(
            model_name='riskallowanceline',
            name='allowance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.allowancetype', verbose_name='भत्ताको प्रकार'),
        ),
        migrations.AlterField(
            model_name='riskallowanceline',
            name='bearer_num',
            field=models.IntegerField(verbose_name='कर्मचारी वा पदाधिकारी संख्या'),
        ),
        migrations.AlterField(
            model_name='riskallowanceline',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='खर्च गर्ने निकायको नाम'),
        ),
        migrations.AlterField(
            model_name='riskallowanceline',
            name='expense_amount',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='सम्म खर्च रकम'),
        ),
        migrations.AlterField(
            model_name='riskallowanceline',
            name='office_bearer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.officebearer', verbose_name='जोखिम भत्ता पाउने पदाधिकारी'),
        ),
        migrations.AlterField(
            model_name='riskallowanceline',
            name='remarks',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='कैफियत'),
        ),
    ]
