# Generated by Django 3.1.4 on 2021-01-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'fund_receipt_expense'), (1, 'risk_allowance'), (2, 'medical_expense'), (3, 'medical_receipt'), (4, 'medical_use'), (5, 'med_purchase_desc'), (6, 'pcr_test_compliance_detail'), (7, 'pcr_lab_detail'), (8, 'rdt_test_detail'), (9, 'pcr_kit_usage'), (10, 'covid_hos_mainpower'), (11, 'cov_hos_equipment'), (12, 'covid_hospital_detail'), (13, 'quarantine_management_detail'), (14, 'isolation_management_detail'), (15, 'quarantine_contruction_expenditure'), (16, 'isolation_construction_expenditure'), (17, 'cov_hos_management_checklist')], default=0),
        ),
    ]
