# Generated by Django 3.1.4 on 2021-01-26 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0002_auto_20210120_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceInstitutionManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProvinceInstitutionManagementLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('major_works', models.TextField(null=True)),
                ('committee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='master_data.committee', verbose_name='समिति: ')),
                ('province_institution_management', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.provinceinstitutionmanagement', verbose_name='संस्थागत व्यवस्था: ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
