# Generated by Django 3.1.4 on 2021-01-20 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('forms', '0002_auto_20210120_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidHospitalManpower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('covidhospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.covidhospital', verbose_name='कोभिड डेडिकेटेड अस्पातालको नाम:: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHospitalManpowerLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_required', models.IntegerField(verbose_name='दरबन्दी संख्या')),
                ('num_hired', models.IntegerField(verbose_name='पदपूर्ति संख्या')),
                ('num_vacant', models.IntegerField(verbose_name='रिक्त संख्या')),
                ('num_contract', models.IntegerField(verbose_name='पदपूर्ति मध्ये करार संख्या')),
                ('covidhospital_manpower_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.covidhospitalmanpower')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('manpower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.manpower', verbose_name='स्वास्थ्य जनशक्ति')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
