# Generated by Django 3.1.4 on 2021-01-21 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('forms', '0002_auto_20210120_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidhospitalequipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_location', to='master_data.location'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='cov_hos_equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitalequipment'),
        ),
        migrations.AlterField(
            model_name='covidhospitalequipment',
            name='cov_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_cov_hos', to='master_data.covidhospital'),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'fund_receipt_expense'), (1, 'risk_allowance'), (2, 'medical_expense'), (3, 'medical_receipt'), (4, 'medical_use'), (5, 'med_purchase_desc'), (6, 'pcr_test_compliance_detail'), (7, 'pcr_lab_detail'), (8, 'rdt_test_detail'), (9, 'pcr_kit_usage'), (10, 'cov_hos_equipment')], default=1),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpense',
            name='fiscal_year_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='fre_fy_from', to='master_data.fiscalyear', verbose_name='सुरु आर्थिक वर्ष'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpense',
            name='fiscal_year_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='fre_fy_to', to='master_data.fiscalyear', verbose_name='अन्त्य आर्थिक वर्ष'),
        ),
    ]
