# Generated by Django 3.1.4 on 2021-01-01 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0009_procurementmethod'),
        ('forms', '0002_change_medical_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_fre_fy_from', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAllowanceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('bearer_num', models.IntegerField(verbose_name='कर्मचारी वा पदाधिकारी संख्या')),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='सम्म खर्च रकम')),
                ('remarks', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='कैफियत')),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.allowancetype', verbose_name='भत्ताको प्रकार')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='खर्च गर्ने निकायको नाम')),
                ('office_bearer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.officebearer', verbose_name='जोखिम भत्ता पाउने पदाधिकारी')),
                ('risk_allowance_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.riskallowance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
