# Generated by Django 3.1.4 on 2021-01-24 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('forms', '0002_auto_20210120_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidHospitalManagementChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.covidhospital', verbose_name='अस्पतालको नामः: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuarantineConstructionExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_quarantine_expense_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_quarantine_expense_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuarantineManagementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_quarantine_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_quarantine_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formcollection',
            name='cov_hos_equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitalequipment'),
        ),
        migrations.AlterField(
            model_name='covidhospitalequipment',
            name='cov_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_cov_hos', to='master_data.covidhospital', verbose_name='अस्पतालको नामः: '),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'fund_receipt_expense'), (1, 'risk_allowance'), (2, 'medical_expense'), (3, 'medical_receipt'), (4, 'medical_use'), (5, 'med_purchase_desc'), (6, 'pcr_test_compliance_detail'), (7, 'pcr_lab_detail'), (8, 'rdt_test_detail'), (9, 'pcr_kit_usage'), (10, 'cov_hos_equipment'), (11, 'quarantine_management_detail'), (12, 'quarantine_contruction_expenditure'), (13, 'cov_hos_management_checklist')], default=1),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpense',
            name='fiscal_year_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='fre_fy_from', to='master_data.fiscalyear', verbose_name='सुरु आर्थिक वर्ष'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpense',
            name='fiscal_year_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='fre_fy_to', to='master_data.fiscalyear', verbose_name='अन्त्य आर्थिक वर्ष'),
        ),
        migrations.AlterField(
            model_name='medicalexpense',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_medExp_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: '),
        ),
        migrations.AlterField(
            model_name='medicalexpense',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_medExp_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: '),
        ),
        migrations.AlterField(
            model_name='medicalpurchasedescription',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_medPurchase_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: '),
        ),
        migrations.AlterField(
            model_name='medicalpurchasedescription',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_medPurchase_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: '),
        ),
        migrations.AlterField(
            model_name='pcrkitusage',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_pcrKit_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: '),
        ),
        migrations.AlterField(
            model_name='pcrkitusage',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_pcrKit_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: '),
        ),
        migrations.AlterField(
            model_name='pcrlaboratorydetail',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_pcr_lab_gov', to='master_data.governmentbody', verbose_name='निकायको नामः: '),
        ),
        migrations.AlterField(
            model_name='pcrlaboratorydetail',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_pcr_lab_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: '),
        ),
        migrations.CreateModel(
            name='QuarantineManagementDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('cost_construction', models.FloatField(verbose_name='निर्माण खर्च')),
                ('num_bed', models.IntegerField(verbose_name='बेड संख्या')),
                ('max_num_daily_stay', models.IntegerField(verbose_name='दैनिकरुपमा बसेको अधिकतम\xa0 संख्या')),
                ('num_stayed_till_fy_end', models.IntegerField(verbose_name='आषाढ मसान्त सम्म क्वारेन्टिनमा बसेकाहरुको कुल संख्या')),
                ('expense_operations', models.FloatField(verbose_name='सञ्चालन ब्यबस्थापन प्रयोजनको खर्च')),
                ('isolation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolation_center', to='master_data.isolationcenter', verbose_name='यस निकायले तयार वा सञ्चालन गरेको क्वारेन्टिन/होल्डिङ सेन्टरको नाम')),
                ('quarantine_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.quarantinemanagementdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuarantineConstructionExpenditureLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('number', models.FloatField(verbose_name='संख्या')),
                ('unit_cost', models.FloatField(verbose_name='प्रति ईकाइ दर')),
                ('amt_expense', models.FloatField(verbose_name='खर्च रकम')),
                ('remarks', models.CharField(blank=True, max_length=50, null=True, verbose_name='कैफियत')),
                ('procure_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_procure', to='master_data.procurementmethod', verbose_name='खरिद विधि')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_product', to='master_data.product', verbose_name='खरिद भएका सामग्री')),
                ('quarantine_construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.quarantineconstructionexpenditure')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_uom', to='master_data.unitofmeasure', verbose_name='इकाई')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHospitalManagementChecklistLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('is_yes', models.BooleanField(default=False, verbose_name='छ')),
                ('remarks', models.CharField(blank=True, max_length=50, null=True, verbose_name='कैफियत')),
                ('cov_hos_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.covidhospitalmanagementchecklist')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.covidhospitalmanagementchecklistdescription', verbose_name='बिबरण')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formcollection',
            name='cov_hos_management_checklist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitalmanagementchecklist'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='quarantine_contruction_expenditure',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.quarantineconstructionexpenditure'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='quarantine_management_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.quarantinemanagementdetail'),
        ),
    ]
