# Generated by Django 3.1.4 on 2021-01-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20210127_1133'),
        ('forms', '0002_alter_medical_receipt_line_inheritance'),
    ]

    operations = [
    ]
