# Generated by Django 3.1.4 on 2021-01-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('forms', '0002_auto_20210127_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidhospitalequipment',
            name='cov_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_cov_hos', to='master_data.covidhospital', verbose_name='कोभिड डेडिकेटेड अस्पातालको नाम:'),
        ),
        migrations.AlterField(
            model_name='medicalexpenseline',
            name='amt_agreement',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='सम्झौता रकम '),
        ),
        migrations.AlterField(
            model_name='medicalexpenseline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='master_data.product', verbose_name='स्वास्थ्य सामाग्री उपकरणको विवरण'),
        ),
        migrations.AlterField(
            model_name='medicaluseline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.product', verbose_name='औषधी स्वास्थ्य सामग्री एवं उपकरणको नाम'),
        ),
        migrations.AlterField(
            model_name='pcrlaboratorydetailline',
            name='time_test_result',
            field=models.FloatField(blank=True, null=True, verbose_name='नतिजा दिन लाग्ने औषत समय'),
        ),
        migrations.DeleteModel(
            name='FormCollection',
        ),
    ]
