# Generated by Django 3.1.4 on 2021-01-26 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('forms', '0002_auto_20210120_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCovidManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dist_quarantine_mgt_body', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dist_quarantine_mgt_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictLabTestLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_rdt_tests', models.IntegerField(verbose_name='आरडीटी परीक्षण')),
                ('num_rdt_results_received', models.IntegerField(verbose_name='आरडीटी नतिजा प्राप्त')),
                ('num_rdt_positive_results', models.IntegerField(verbose_name='आरडीटी पोजेटिभ नतिजा')),
                ('num_pcr_tests', models.IntegerField(verbose_name='पीसीआर परीक्षण')),
                ('num_pcr_results_received', models.IntegerField(verbose_name='पीसीआर नतिजा प्राप्त')),
                ('num_pcr_positive_results', models.IntegerField(verbose_name='पीसीआर पोजेटिभ नतिजा')),
                ('num_pcr_contract_trace', models.IntegerField(verbose_name='पीसीआर परीक्षण मध्ये कन्ट्रयाक ट्रेसिङ्गको आधारमा गरेको परीक्षण')),
                ('num_covid_treated_patients', models.IntegerField(verbose_name='उपचार गराएका कोरोना विरामी संख्या')),
                ('num_covid_recovered_patients', models.IntegerField(verbose_name='उपचार पछि निको भई घर गएको संख्या')),
                ('num_isolation_treatments', models.IntegerField(verbose_name='आइसोलेसनमा उपचार गराउने संख्या')),
                ('num_icu_treatments', models.IntegerField(verbose_name='आई सी यु मा उपचार गराउने संख्या')),
                ('num_covid_deaths', models.IntegerField(verbose_name='मृत्यु हुनेको संख्या')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dist_labtest_mgt', to='master_data.district', verbose_name='जिल्ला')),
                ('lab_test_lines', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.districtcovidmanagement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictIsolationManagementLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_prepared_icu', models.IntegerField(verbose_name='तयारी अवस्थामा रहेको icu  संख्या')),
                ('num_prepared_bed', models.IntegerField(verbose_name='तयारी अवस्थामा रहेको बेड संख्या')),
                ('num_infected_person', models.IntegerField(verbose_name='संक्रमित संख्या')),
                ('num_isolated_person', models.IntegerField(verbose_name='आईसोलेशनमा बस्नेको संख्या')),
                ('num_home_isolated_person', models.IntegerField(verbose_name='होम आईसोलेशनमा बस्नेको संख्या')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dist_isolation_mgt', to='master_data.district', verbose_name='जिल्ला')),
                ('isolation_mgmt_lines', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.districtcovidmanagement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisctrictQuarantineManagementLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_prepared_quarantine', models.IntegerField(verbose_name='तयार गरेको क्वारेन्टीन संख्या')),
                ('num_prepared_quarantine_beds', models.IntegerField(verbose_name='तयार गरेको क्वारेन्टीन बेड संख्या')),
                ('num_quarantined_person', models.IntegerField(verbose_name='क्वारेन्टीन बसेका व्यक्तिको संख्या')),
                ('num_home_quarantined_person', models.IntegerField(verbose_name='होम क्वारेन्टिनमा बसेका व्यक्तिको संख्या')),
                ('num_insufficient_bed', models.IntegerField(verbose_name='नपुग वेड संख्या')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dist_quarantine_mgt', to='master_data.district', verbose_name='जिल्ला')),
                ('quarantine_mgmgt_lines', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.districtcovidmanagement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
