# Generated by Django 3.1.4 on 2021-01-12 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0009_procurementmethod'),
        ('forms', '0003_riskallowance_riskallowanceline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPurchaseDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_medPurchase_gov', to='master_data.governmentbody')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_medPurchase_fy', to='master_data.fiscalyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalPurchaseDescriptionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('product_specificaiton', models.CharField(blank=True, max_length=255, null=True, verbose_name='सामानको छोटो स्पेशिफिकेशन')),
                ('date_procure_agreement', models.CharField(default='01/01/2000', max_length=15, verbose_name='खरिद सम्झौता मिति')),
                ('date_received', models.CharField(default='01/01/2000', max_length=15, verbose_name='सामान प्राप्त मिति')),
                ('qty', models.FloatField(blank=True, null=True, verbose_name='परीमाण')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='दर')),
                ('total_amt', models.FloatField(blank=True, null=True, verbose_name='कुल रकम')),
                ('medical_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.medicalpurchasedescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.product', verbose_name='सामानको नाम')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.unitofmeasure', verbose_name='इकाई')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
