# Generated by Django 3.1.4 on 2021-01-28 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('forms', '0003_fund_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardReliefProcureDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ward_relief', to='master_data.governmentbody', verbose_name='निकायको नामः')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ward_relief', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WardReliefProcureDistributionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('ward_num', models.IntegerField(verbose_name='वडा नं')),
                ('amt_relief_material_purchase', models.FloatField(verbose_name='राहत सामग्री खरिद रकम')),
                ('relief_beneficiary_family', models.CharField(max_length=500, verbose_name='राहत लाभग्राही परिवार')),
                ('num_relief_benefitted', models.IntegerField(verbose_name='उपलव्ध गराएको राहतबाट सुविधा प्राप्त जनसंख्या')),
                ('remarks', models.CharField(max_length=100, verbose_name='केही व्यहोरा भए खुलाउने ')),
                ('procure_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_relief_line', to='master_data.procurementmethod', verbose_name='खरिद विधि')),
                ('ward_relief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.wardreliefprocuredistribution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
