# Generated by Django 3.1.4 on 2021-01-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_procurementmethod'),
        ('forms', '0003_riskallowance_riskallowanceline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalexpense',
            name='body',
        ),
        migrations.RemoveField(
            model_name='medicalexpense',
            name='fiscal_year',
        ),
        migrations.CreateModel(
            name='FormCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_medExp_gov', to='master_data.governmentbody')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_medExp_fy', to='master_data.fiscalyear')),
            ],
        ),
        migrations.AddField(
            model_name='medicalexpense',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='forms.formcollection'),
        ),
    ]
