# Generated by Django 3.1.4 on 2021-01-24 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_epidemicoutbreakpreparatorywork'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemicoutbreakpreparatorywork',
            name='state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='epidemic_outbreak_preparatory_work',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.epidemicoutbreakpreparatorywork'),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'fund_receipt_expense'), (1, 'risk_allowance'), (2, 'medical_expense'), (3, 'medical_receipt'), (4, 'medical_use'), (5, 'med_purchase_desc'), (6, 'pcr_test_compliance_detail'), (7, 'pcr_lab_detail'), (8, 'rdt_test_detail'), (9, 'pcr_kit_usage'), (10, 'epidemic_outbreak_preparatory')], default=1),
        ),
    ]
