# Generated by Django 3.1.4 on 2021-01-21 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0003_covidhopsital_mainpower'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidHospitalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covid_hospital_details', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covid_hospital_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHospitalDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('announce_time_health_workers', models.IntegerField(verbose_name='कोभिड अस्पताल घोषणा हुँदाको अवस्थामा रहेको स्वास्थ्यकर्मीको संख्या')),
                ('announce_time_beds', models.IntegerField(verbose_name='कोभिड अस्पताल घोषणा हुँदाको अवस्थामा रहेको बेड संख्या')),
                ('announce_time_icu', models.IntegerField(verbose_name='कोभिड अस्पताल घोषणा हुँदाको अवस्थामा रहेको आई सी यु संख्या')),
                ('announce_time_ventilators', models.IntegerField(verbose_name='कोभिड अस्पताल घोषणा हुँदाको अवस्थामा रहेको भेन्टिलेटर संख्या')),
                ('added_health_workers', models.IntegerField(verbose_name='२०७७ असार मसान्तसम्म थप भएको स्वास्थ्यकर्मीको संख्या')),
                ('added_beds', models.IntegerField(verbose_name='२०७७ असार मसान्तसम्म थप भएको बेड संख्या')),
                ('added_icu', models.IntegerField(verbose_name='२०७७ असार मसान्तसम्म थप भएको आई सी यु संख्या')),
                ('added_ventilators', models.IntegerField(verbose_name='२०७७ असार मसान्तसम्म थप भएको भेन्टिलेटर संख्या')),
                ('num_treated_patients', models.IntegerField(verbose_name='२०७७ असार मसान्तसम्म उपचार गरेको कोभिड विरामी संख्या')),
                ('expense_treatment', models.FloatField(verbose_name='२०७७ असार मसान्तसम्म उपचारमा भएको खर्च')),
                ('covidhospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.covidhospital', verbose_name='डेडिकेटेड अस्पतालको नाम र स्थान')),
                ('covidhospital_hospital_detail_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.covidhospitaldetail')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
