# Generated by Django 3.1.4 on 2021-01-24 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_epidemicoutbreakpreparatorywork'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemicoutbreakpreparatorywork',
            name='state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25),
        ),
    ]
