# Generated by Django 3.1.4 on 2021-01-12 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0009_procurementmethod'),
        ('forms', '0003_riskallowance_riskallowanceline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_receipt', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalReceiptLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('quantity', models.IntegerField(verbose_name='परिमाण')),
                ('cost_received_items', models.FloatField(verbose_name='प्राप्त औषधी स्वास्थ्य सामग्री उपकरणको मूल्य')),
                ('usage_situation', models.CharField(max_length=300, verbose_name='प्रयोगको अवस्था')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('medical_receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.medicalreceipt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.product', verbose_name='स्वास्थ्य सामाग्री उपकरणको विवरण')),
                ('provider_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body_pro', to='master_data.governmentbody', verbose_name='प्रदान गर्ने निकाय वा संस्था')),
                ('provider_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_pro', to='master_data.institution', verbose_name='प्रदान गर्ने निकाय वा संस्था')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
