# Generated by Django 3.1.4 on 2021-01-22 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('forms', '0004_auto_20210121_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidHospitalManagementChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'fund_receipt_expense'), (1, 'risk_allowance'), (2, 'medical_expense'), (3, 'medical_receipt'), (4, 'medical_use'), (5, 'med_purchase_desc'), (6, 'pcr_test_compliance_detail'), (7, 'pcr_lab_detail'), (8, 'rdt_test_detail'), (9, 'pcr_kit_usage'), (10, 'cov_hos_equipment'), (11, 'quarantine_management_detail'), (12, 'quarantine_contruction_expenditure'), (13, 'cov_hos_management_checklist')], default=1),
        ),
        migrations.CreateModel(
            name='CovidHospitalManagementChecklistLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('is_yes', models.BooleanField(default=False, verbose_name='छ ?')),
                ('remarks', models.CharField(blank=True, max_length=50, null=True, verbose_name='कैफियत')),
                ('cov_hos_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.covidhospitalmanagementchecklist')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='बिबरण', to='master_data.covidhospitalmanagementchecklistdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formcollection',
            name='cov_hos_management_checklist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitalmanagementchecklistline'),
        ),
    ]
