# Generated by Django 3.1.4 on 2021-01-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_medical_use_line_add_related_name_medical_use_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidhospitalmanpowerline',
            name='covidhospital_manpower_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.covidhospitalmanpower'),
        ),
        migrations.AlterField(
            model_name='isolationconstructionexependitureline',
            name='isolation_cons_expentiture_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.isolationconstructionexependiture'),
        ),
        migrations.AlterField(
            model_name='isolationmanagementdetailline',
            name='isolation_management_detail_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.isolationmanagementdetail'),
        ),
        migrations.AlterField(
            model_name='pcrtestcompliancedetailline',
            name='pcrtest_compliance_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.pcrtestcompliancedetail'),
        ),
        migrations.AlterField(
            model_name='rdttestdetailline',
            name='rdt_test_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.rdttestdetail'),
        ),
    ]
