# Generated by Django 3.1.4 on 2021-01-13 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_procurementmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0004_medicalpurchasedescription_medicalpurchasedescriptionline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcrLaboratoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_pcr_lab_gov', to='master_data.governmentbody')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_pcr_lab_fy', to='master_data.fiscalyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrLaboratoryDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_tested_fy_end', models.IntegerField(blank=True, null=True, verbose_name='आषाढ मसान्तसम्म परीक्षण गरेको कुल संख्या')),
                ('num_infected', models.IntegerField(blank=True, null=True, verbose_name='परीक्षण मध्ये संक्रमितको संख्या')),
                ('time_test_result', models.FloatField(blank=True, null=True, verbose_name='दनतिजा दिन लाग्ने औषत समय')),
                ('expense_pcr_test', models.FloatField(blank=True, null=True, verbose_name='पीसीआर परीक्षणमा आषाढ समान्त सम्म भएको खर्च')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.laboratory', verbose_name='पीसीआर ल्यावको नाम र स्थान')),
                ('pcr_lab_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.pcrlaboratorydetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
