# Generated by Django 3.1.4 on 2021-01-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_procurementmethod'),
        ('forms', '0004_medical_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreceiptline',
            name='provider_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body_pro', to='master_data.governmentbody', verbose_name='प्रदान गर्ने निकाय'),
        ),
        migrations.AlterField(
            model_name='medicalreceiptline',
            name='provider_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_pro', to='master_data.institution', verbose_name='प्रदान गर्ने संस्था'),
        ),
    ]
