# Generated by Django 3.1.4 on 2021-01-28 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0004_wardrelief'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedReliefDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivedrelief', to='master_data.governmentbody', verbose_name='निकायको नामः')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivedrelief', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष:')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivedReliefDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('qty_received', models.FloatField(verbose_name='प्राप्त परिमाण')),
                ('qty_distributed', models.FloatField(verbose_name='वितरण परिमाण')),
                ('qty_remaining', models.FloatField(verbose_name='बाँकी परिमाण ')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedrelief', to='master_data.institution', verbose_name='राहत सामग्री प्रदान गर्नेको नाम')),
                ('relief_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_relief_line', to='master_data.product', verbose_name='राहत सामग्री')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedrelief', to='master_data.unitofmeasure', verbose_name='ईकाइ')),
                ('ward_relief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.receivedreliefdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
