# Generated by Django 3.1.4 on 2021-01-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_procurementmethod'),
        ('forms', '0004_add_form_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formcollection',
            name='body',
        ),
        migrations.RemoveField(
            model_name='formcollection',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='medicalexpense',
            name='collection',
        ),
        migrations.AddField(
            model_name='formcollection',
            name='med_exp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicalexpense'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='risk_allowance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.riskallowance'),
        ),
        migrations.AddField(
            model_name='medicalexpense',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_medExp_gov', to='master_data.governmentbody'),
        ),
        migrations.AddField(
            model_name='medicalexpense',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_medExp_fy', to='master_data.fiscalyear'),
        ),
    ]
