# Generated by Django 3.1.4 on 2021-01-21 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('forms', '0004_covidhospital_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolationManagementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iso_management_body', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iso_management_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IsolationManagementDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('cost_construction', models.FloatField(verbose_name='निर्माण खर्च ')),
                ('num_bed', models.IntegerField(verbose_name='बेड संख्या')),
                ('max_num_daily_stay', models.IntegerField(verbose_name='आईसोलेशन केन्द्रमा बस्नेहरुको दैनिकरुपमा बसेको अधिकतम  संख्या')),
                ('num_stayed_till_fy_end', models.IntegerField(verbose_name='आईसोलेशन केन्द्रमा बस्नेहरुको आषाढ मसान्त सम्म आईसोलेशन केन्द्रमा बसेकाहरुको कुल संख्या')),
                ('expense_operations', models.FloatField(verbose_name='ब्यबस्थापन प्रयोजनको खर्च')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('isolation_management_detail_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.isolationmanagementdetail')),
                ('isolationcenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.isolationcenter', verbose_name='यस निकायले तयार वा सञ्चालन गरेको आईसोलेशन केन्द्रको नाम')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
