# Generated by Django 3.1.4 on 2021-01-24 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('forms', '0004_state_field_add_on_epidemic_outbreak'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlanImplementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionPlanImplementationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('work_done', models.CharField(max_length=500, verbose_name='काम सकियो')),
                ('work_expense', models.FloatField(verbose_name='काम खर्च')),
                ('action_plan_implementation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.actionplanimplementation', verbose_name='कार्य योजना कार्यान्वयन')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.actionplanactivity', verbose_name='कार्य योजना गतिविधि')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
