# Generated by Django 3.1.4 on 2021-01-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_action_plan_implementation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcollection',
            name='action_plan_implementation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.actionplanimplementation'),
        ),
    ]
