# Generated by Django 3.1.4 on 2021-01-22 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0005_isolation_management_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolationConstructionExependiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iso_centerexpentiture', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iso_cenexpentiture_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formcollection',
            name='IsolationManagementDetail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.isolationmanagementdetail'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='cov_hos_equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitalequipment'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='covid_hos_mainpower',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitalmanpower'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='covid_hospital_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitaldetail'),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'fund_receipt_expense'), (1, 'risk_allowance'), (2, 'medical_expense'), (3, 'medical_receipt'), (4, 'medical_use'), (5, 'med_purchase_desc'), (6, 'pcr_test_compliance_detail'), (7, 'pcr_lab_detail'), (8, 'rdt_test_detail'), (9, 'pcr_kit_usage'), (10, 'covid_hos_mainpower'), (11, 'covidhospitaldetail'), (12, 'isolationmanagementdetail')], default=1),
        ),
        migrations.CreateModel(
            name='IsolationConstructionExependitureLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('number', models.FloatField(verbose_name='संख्या')),
                ('unit_cost', models.FloatField(verbose_name='प्रति ईकाइ दर')),
                ('amt_expense', models.FloatField(verbose_name='खर्च रकम')),
                ('remarks', models.CharField(max_length=300, verbose_name='कैफियत')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('isolation_cons_expentiture_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.isolationconstructionexependiture')),
                ('oum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasure', verbose_name='इकाई')),
                ('procure_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.procurementmethod', verbose_name='खरिद विधि')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.product', verbose_name='खरिद भएका सामग्री')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
