# Generated by Django 3.1.4 on 2021-01-28 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('forms', '0005_relief_procure_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefProcurementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relief_body', to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relief_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReliefProcurementDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('amt_purchase', models.FloatField(verbose_name='खरिद रकम')),
                ('reason_procure_method', models.CharField(max_length=300, verbose_name='उक्त खरिद विधि प्रयोग गर्नाको कारण')),
                ('procure_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_investigation_body', to='master_data.procurementmethod', verbose_name='राहात सामग्री खरिद गर्दा प्रयोग गरेको विधि: ')),
                ('reliefprocurementdetail_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.reliefprocurementdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
