# Generated by Django 3.1.4 on 2021-01-18 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_procurementmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0005_pcrlaboratorydetail_pcrlaboratorydetailline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcrKitUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_pcrKit_gov', to='master_data.governmentbody')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_pcrKit_fy', to='master_data.fiscalyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrKitUsageLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_kit_received', models.IntegerField(blank=True, null=True, verbose_name='२०७६ चैत्र देखि २०७७ आषाढ सम्म पिसीआर किट प्राप्ती')),
                ('num_kit_expensed', models.IntegerField(blank=True, null=True, verbose_name='२०७७ आषाढमसान्त सम्म पीसिआर किट खर्च')),
                ('num_kit_available', models.IntegerField(blank=True, null=True, verbose_name='२०७७ आषाढमसान्त मौजदात किट')),
                ('num_tests', models.IntegerField(blank=True, null=True, verbose_name='परीक्षण संख्या')),
                ('num_wasted', models.IntegerField(blank=True, null=True, verbose_name='वेष्टेज गएको किट संख्या')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.laboratory', verbose_name='प्रयोगशालाको नाम')),
                ('pcr_kit_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.pcrkitusage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
