# Generated by Django 3.1.4 on 2021-01-28 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0005_received_relief'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefDistributionExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reliefdistribution', to='master_data.governmentbody', verbose_name='निकायको नामः')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reliefdistribution', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReliefDistributionExpenseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('amt_expense', models.FloatField(verbose_name='खर्च रकम')),
                ('num_relif_beneficiary', models.IntegerField(verbose_name='राहात पाउनेको संख्या')),
                ('remarks', models.CharField(max_length=100, verbose_name='कैफियत')),
                ('relief_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.reliefdistributionexpense')),
                ('relief_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reliefdistributionline', to='master_data.relieftype', verbose_name='राहातको प्रकार')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
