# Generated by Django 3.1.4 on 2021-01-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_formcollection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'risk_forms'), (2, 'med_forms')], default=1, max_length=25),
        ),
    ]
