# Generated by Django 3.1.4 on 2021-01-18 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_procurementmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0006_pcrkitusage_pcrkitusageline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidHospitalEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('cov_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_cov_hos', to='master_data.covidhospital')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_location', to='master_data.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CovidHospitalEquipmentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_required', models.IntegerField(blank=True, null=True, verbose_name='आबश्यक')),
                ('available', models.IntegerField(blank=True, null=True, verbose_name='उपलब्ध')),
                ('num_still_required', models.IntegerField(blank=True, null=True, verbose_name='नपुग')),
                ('cov_hos_equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.covidhospitalequipment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.product', verbose_name='स्वास्थ्य उपकरण')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
