# Generated by Django 3.1.4 on 2021-01-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('forms', '0006_case_investigation_tracing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinvestigationtracingline',
            name='description',
            field=models.TextField(verbose_name='बिबरण'),
        ),
        migrations.AlterField(
            model_name='caseinvestigationtracingline',
            name='num_identified_infection',
            field=models.IntegerField(verbose_name='खोज पडतालबाट पहिचान भएका संक्रमित'),
        ),
        migrations.AlterField(
            model_name='caseinvestigationtracingline',
            name='num_searched_cases',
            field=models.IntegerField(verbose_name='खोज पडताल गरिएका केश संख्या'),
        ),
        migrations.AlterField(
            model_name='caseinvestigationtracingline',
            name='num_team_members',
            field=models.PositiveIntegerField(verbose_name='टिम गठन संख्या '),
        ),
        migrations.AlterField(
            model_name='epidemicoutbreakpreparatorywork',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः'),
        ),
    ]
