# Generated by Django 3.1.4 on 2021-01-14 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_procurementmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0006_medical_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcrTestComplianceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                           to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                  related_name='pctr_test_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PcrTestComplianceDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('month', models.IntegerField(blank=True, choices=[(1, 'वैशाख'), (2, 'जेष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'आश्विन'), (
                    7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फाल्गुण'), (12, 'चैत्र')], null=True, verbose_name='महिना')),
                ('year', models.IntegerField(verbose_name='बर्ष:')),
                ('all_area_test_num', models.IntegerField(
                    verbose_name='सबै क्षेत्रमा गरेको कुल परीक्षण संख्या')),
                ('all_area_infected_num', models.IntegerField(
                    verbose_name='सबै क्षेत्रमा गरेको कुल संक्रमित संख्या')),
                ('priority_1_test_num', models.IntegerField(
                    verbose_name='Priority-1क्षेत्रमा गरेको परीक्षण संख्या')),
                ('priority_1_infected_num', models.IntegerField(
                    verbose_name='Priority-1 क्षेत्रमा गरेको संक्रमित संख्या')),
                ('priority_2_test_num', models.IntegerField(
                    verbose_name='Priority-2 क्षेत्रमा गरेको परीक्षण संख्या')),
                ('priority_2_infected_num', models.IntegerField(
                    verbose_name='Priority-2 क्षेत्रमा गरेको संक्रमित संख्या')),
                ('priority_3_test_num', models.IntegerField(
                    verbose_name='Priority-3 क्षेत्रमा गरेको परीक्षण संख्या')),
                ('priority_3_infected_num', models.IntegerField(
                    verbose_name='Priority-3 क्षेत्रमा गरेको संक्रमित संख्या')),
                ('non_priority_test_num', models.IntegerField(
                    verbose_name='Non-priority  क्षेत्रमा गरेको परीक्षण संख्या')),
                ('non_priority_infected_num', models.IntegerField(
                    verbose_name='Non-priority  क्षेत्रमा गरेको संक्रमित संख्या')),
                ('create_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pcrtest_compliance_detail', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='forms.pcrtestcompliancedetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
