# Generated by Django 3.1.4 on 2021-01-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_isolationconstructionexpenditure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidhospitaldetailline',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='covidhospitalmanpowerline',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='isolationconstructionexependitureline',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='isolationmanagementdetailline',
            name='create_user',
        ),
    ]
