# Generated by Django 3.1.4 on 2021-01-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_case_investigation_tracing'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcollection',
            name='case_investigation_tracing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.caseinvestigationtracing'),
        ),
    ]
