# Generated by Django 3.1.4 on 2021-01-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_formcollection_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskallowance',
            old_name='fiscal_year_from',
            new_name='fiscal_year',
        ),
        migrations.AddField(
            model_name='riskallowance',
            name='state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25),
        ),
    ]
