# Generated by Django 3.1.4 on 2021-01-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_covidhospitalequipment_covidhospitalequipmentline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidhospitalequipment',
            name='state',
        ),
        migrations.RemoveField(
            model_name='medicalpurchasedescription',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pcrkitusage',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pcrlaboratorydetail',
            name='state',
        ),
    ]
