# Generated by Django 3.1.4 on 2021-01-14 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0009_procurementmethod'),
        ('forms', '0007_pctr_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdtTestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdt_test_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pcrtestcompliancedetailline',
            name='all_area_infected_num',
            field=models.IntegerField(verbose_name='सबै क्षेत्रमा गरेको कुल  संक्रमित संख्या'),
        ),
        migrations.CreateModel(
            name='RdtTestDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_tested_fy_end', models.IntegerField(verbose_name='आषाढ मसान्तसम्म आरडीटी परीक्षण गरेको संख्या')),
                ('num_tested_pcr', models.IntegerField(verbose_name='परीक्षण मध्ये पिसीआर गरिएको संख्या')),
                ('expense_rdt_test', models.IntegerField(verbose_name='आरडीटी परीक्षणमा आषाढ समान्त सम्म भएको खर्च')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.laboratory', verbose_name='ल्यावको नाम र स्थान')),
                ('rdt_test_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.rdttestdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
