# Generated by Django 3.1.4 on 2021-01-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('forms', '0007_alter_case_investigation_tracing'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalexpenseline',
            name='importer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='master_data.importer'),
        ),
        migrations.AddField(
            model_name='medicalexpenseline',
            name='procure_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='master_data.procurementmethod'),
        ),
        migrations.AlterField(
            model_name='medicalexpenseline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='master_data.product', verbose_name='स्वास्थ्य सामाग्री उपकरणको विवरण'),
        ),
    ]
