# Generated by Django 3.1.4 on 2021-01-28 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_case_investigation_tracing'),
        ('forms', '0005_district_covid_management'),
    ]

    operations = [
    ]
