# Generated by Django 3.1.4 on 2021-01-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_procurementmethod'),
        ('forms', '0008_rename_fy_risk_allowance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskallowanceline',
            old_name='body',
            new_name='gov_body',
        ),
        migrations.RemoveField(
            model_name='riskallowanceline',
            name='risk_allowance_line',
        ),
        migrations.AddField(
            model_name='riskallowanceline',
            name='risk_allowance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.riskallowance'),
        ),
        migrations.AlterField(
            model_name='riskallowance',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: '),
        ),
        migrations.AlterField(
            model_name='riskallowance',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_fre_fy_from', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: '),
        ),
    ]
