# Generated by Django 3.1.4 on 2021-01-20 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0011_auto_20210117_0659'),
        ('forms', '0008_rdt_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpidemicOutbreakPreparatoryWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः: ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epidemic_outbreak_preparatory_work', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष: ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EpidemicOutbreakPreparatoryWorkLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('preparation_work_to_do', models.CharField(max_length=500, verbose_name='काम गर्न तयारी कार्य')),
                ('major_activities', models.CharField(max_length=500, verbose_name='प्रमुख कार्य')),
                ('amt_expense', models.FloatField(verbose_name='खर्च रकम')),
                ('epidemic_outbreak_preparatory_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.epidemicoutbreakpreparatorywork', verbose_name='महामारीको प्रकोप तयारी कार्य')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
