# Generated by Django 3.1.4 on 2021-01-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_merge_20210128_1056'),
        ('forms', '0003_add_province_institution_management_and_line'),
    ]

    operations = [
    ]
