# Generated by Django 3.1.4 on 2021-01-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('forms', '0009_alter_medicalexpenseline_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaluse',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नाम'),
        ),
        migrations.AlterField(
            model_name='medicaluse',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_use', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष'),
        ),
        migrations.AlterField(
            model_name='medicaluseline',
            name='is_purchased',
            field=models.BooleanField(default=False, verbose_name='खरिद वा प्राप्ती? यदि खरीद गरिएको भए टिक गर्नुहोस्'),
        ),
        migrations.AlterField(
            model_name='rdttestdetailline',
            name='expense_rdt_test',
            field=models.IntegerField(default=0, verbose_name='आरडीटी परीक्षणमा आषाढ समान्त सम्म भएको खर्च'),
        ),
        migrations.AlterField(
            model_name='rdttestdetailline',
            name='num_tested_fy_end',
            field=models.IntegerField(default=0, verbose_name='आषाढ मसान्तसम्म आरडीटी परीक्षण गरेको संख्या'),
        ),
        migrations.AlterField(
            model_name='rdttestdetailline',
            name='num_tested_pcr',
            field=models.IntegerField(default=0, verbose_name='परीक्षण मध्ये पिसीआर गरिएको संख्या'),
        ),
    ]
