# Generated by Django 3.1.4 on 2021-01-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20210108_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcollection',
            name='status',
            field=models.IntegerField(choices=[(1, 'START'), (2, 'INCOMPLETE'), (3, 'cOMPLETE')], default=1),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'risk_forms'), (2, 'med_forms')], default=1),
        ),
    ]
