# Generated by Django 3.1.4 on 2021-01-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('forms', '0009_merge_20210128_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceinstitutionmanagement',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नामः '),
        ),
    ]
