# Generated by Django 3.1.4 on 2021-01-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_form_collection_alter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcollection',
            name='status',
            field=models.IntegerField(choices=[(1, 'START'), (2, 'INCOMPLETE'), (3, 'COMPLETE')], default=1),
        ),
    ]
