# Generated by Django 3.1.4 on 2021-01-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20210128_1456'),
        ('forms', '0006_relief_distribution'),
    ]

    operations = [
    ]
