# Generated by Django 3.1.4 on 2021-01-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_rdttestdetailline_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidhospitaldetailline',
            name='date_announcement',
            field=models.DateField(null=True),
        ),
    ]
