# Generated by Django 3.1.4 on 2021-01-29 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('forms', '0011_alter_covidhospitaldetailline_date_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarantinemanagementdetailline',
            name='isolation_center',
        ),
        migrations.AddField(
            model_name='quarantinemanagementdetailline',
            name='quarantine_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_center', to='master_data.quanrantinecenter', verbose_name='यस निकायले तयार वा सञ्चालन गरेको क्वारेन्टिन/होल्डिङ सेन्टरको नाम'),
        ),
    ]
