# Generated by Django 3.1.4 on 2021-01-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_merge_20210129_1055'),
        ('forms', '0006_relief_procurement_details'),
    ]

    operations = [
    ]
