# Generated by Django 3.1.4 on 2021-01-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20210111_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskallowanceline',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='कैफियत'),
        ),
    ]
