# Generated by Django 3.1.4 on 2021-01-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_merge_20210129_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseinvestigationtracingoperationsline',
            old_name='body',
            new_name='case_invs_body',
        ),
    ]
