# Generated by Django 3.1.4 on 2021-01-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_alter_quarantinemanagementdetailline_quarantinecenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isolationconstructionexependitureline',
            old_name='oum',
            new_name='uom',
        ),
    ]
