# Generated by Django 3.1.4 on 2021-01-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_rdt_test'),
        ('forms', '0013_alter_collection_status'),
    ]

    operations = [
    ]
