# Generated by Django 3.1.4 on 2021-01-18 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_merge_20210118_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formcollection',
            old_name='med_exp',
            new_name='medical_expense',
        ),
        migrations.AddField(
            model_name='formcollection',
            name='medical_receipt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicalreceipt'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='pcr_test_compliance_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.pcrtestcompliancedetail'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='rdt_test_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.rdttestdetail'),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'risk_allowance'), (1, 'medical_expense'), (2, 'medical_receipt'), (3, 'pcr_test_compliance_detail'), (4, 'rdt_test_detail')], default=1),
        ),
    ]
