# Generated by Django 3.1.4 on 2021-01-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('forms', '0014_merge_20210129_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexpenseline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='master_data.product', verbose_name='स्वास्थ्य सामाग्री उपकरण'),
        ),
    ]
