# Generated by Django 3.1.4 on 2021-01-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_alter_formcollection_addforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcollection',
            name='medical_use',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicaluse'),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'risk_allowance'), (1, 'medical_expense'), (2, 'medical_receipt'), (3, 'medical_use'), (4, 'pcr_test_compliance_detail'), (5, 'rdt_test_detail')], default=1),
        ),
    ]
