# Generated by Django 3.1.4 on 2021-01-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_alter_hospital_body_inheritaddress'),
        ('forms', '0013_auto_20210129_1347'),
    ]

    operations = [
    ]
