# Generated by Django 3.1.4 on 2021-01-31 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_alter_hospital_body_inheritaddress'),
        ('forms', '0016_merge_20210129_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disctrictquarantinemanagementline',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dist_quarantine_mgt', to='master_data.district', verbose_name='जिल्ला'),
        ),
        migrations.AlterField(
            model_name='disctrictquarantinemanagementline',
            name='num_home_quarantined_person',
            field=models.IntegerField(null=True, verbose_name='होम क्वारेन्टिनमा बसेका व्यक्तिको संख्या'),
        ),
        migrations.AlterField(
            model_name='disctrictquarantinemanagementline',
            name='num_insufficient_bed',
            field=models.IntegerField(null=True, verbose_name='नपुग वेड संख्या'),
        ),
        migrations.AlterField(
            model_name='disctrictquarantinemanagementline',
            name='num_prepared_quarantine',
            field=models.IntegerField(null=True, verbose_name='तयार गरेको क्वारेन्टीन संख्या'),
        ),
        migrations.AlterField(
            model_name='disctrictquarantinemanagementline',
            name='num_prepared_quarantine_beds',
            field=models.IntegerField(null=True, verbose_name='तयार गरेको क्वारेन्टीन बेड संख्या'),
        ),
        migrations.AlterField(
            model_name='disctrictquarantinemanagementline',
            name='num_quarantined_person',
            field=models.IntegerField(null=True, verbose_name='क्वारेन्टीन बसेका व्यक्तिको संख्या'),
        ),
        migrations.AlterField(
            model_name='districtisolationmanagementline',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dist_isolation_mgt', to='master_data.district', verbose_name='जिल्ला'),
        ),
        migrations.AlterField(
            model_name='districtisolationmanagementline',
            name='num_home_isolated_person',
            field=models.IntegerField(null=True, verbose_name='होम आईसोलेशनमा बस्नेको संख्या'),
        ),
        migrations.AlterField(
            model_name='districtisolationmanagementline',
            name='num_infected_person',
            field=models.IntegerField(null=True, verbose_name='संक्रमित संख्या'),
        ),
        migrations.AlterField(
            model_name='districtisolationmanagementline',
            name='num_isolated_person',
            field=models.IntegerField(null=True, verbose_name='आईसोलेशनमा बस्नेको संख्या'),
        ),
        migrations.AlterField(
            model_name='districtisolationmanagementline',
            name='num_prepared_bed',
            field=models.IntegerField(null=True, verbose_name='तयारी अवस्थामा रहेको बेड संख्या'),
        ),
        migrations.AlterField(
            model_name='districtisolationmanagementline',
            name='num_prepared_icu',
            field=models.IntegerField(null=True, verbose_name='तयारी अवस्थामा रहेको icu  संख्या'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dist_labtest_mgt', to='master_data.district', verbose_name='जिल्ला'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_covid_deaths',
            field=models.IntegerField(null=True, verbose_name='मृत्यु हुनेको संख्या'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_covid_recovered_patients',
            field=models.IntegerField(null=True, verbose_name='उपचार पछि निको भई घर गएको संख्या'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_covid_treated_patients',
            field=models.IntegerField(null=True, verbose_name='उपचार गराएका कोरोना विरामी संख्या'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_icu_treatments',
            field=models.IntegerField(null=True, verbose_name='आई सी यु मा उपचार गराउने संख्या'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_isolation_treatments',
            field=models.IntegerField(null=True, verbose_name='आइसोलेसनमा उपचार गराउने संख्या'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_pcr_contract_trace',
            field=models.IntegerField(null=True, verbose_name='पीसीआर परीक्षण मध्ये कन्ट्रयाक ट्रेसिङ्गको आधारमा गरेको परीक्षण'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_pcr_positive_results',
            field=models.IntegerField(null=True, verbose_name='पीसीआर पोजेटिभ नतिजा'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_pcr_results_received',
            field=models.IntegerField(null=True, verbose_name='पीसीआर नतिजा प्राप्त'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_pcr_tests',
            field=models.IntegerField(null=True, verbose_name='पीसीआर परीक्षण'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_rdt_positive_results',
            field=models.IntegerField(null=True, verbose_name='आरडीटी पोजेटिभ नतिजा'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_rdt_results_received',
            field=models.IntegerField(null=True, verbose_name='आरडीटी नतिजा प्राप्त'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='num_rdt_tests',
            field=models.IntegerField(null=True, verbose_name='आरडीटी परीक्षण'),
        ),
    ]
