# Generated by Django 3.1.4 on 2021-01-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_alter_formcollection_add_medicaluse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaluseline',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='pcrtestcompliancedetailline',
            name='create_user',
        ),
        migrations.AlterField(
            model_name='medicaluseline',
            name='is_purchased',
            field=models.BooleanField(default=False, verbose_name='खरीद गरिएको ?'),
        ),
    ]
