# Generated by Django 3.1.4 on 2021-02-01 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_alter_districtcovidmanagement_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidhospitaldetailline',
            name='covidhospital_hospital_detail_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.covidhospitaldetail'),
        ),
        migrations.AlterField(
            model_name='covidhospitalmanpowerline',
            name='covidhospital_manpower_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.covidhospitalmanpower'),
        ),
        migrations.AlterField(
            model_name='disctrictquarantinemanagementline',
            name='quarantine_mgmgt_lines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.districtcovidmanagement'),
        ),
        migrations.AlterField(
            model_name='epidemicoutbreakpreparatoryworkline',
            name='epidemic_outbreak_preparatory_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.epidemicoutbreakpreparatorywork', verbose_name='महामारीको प्रकोप तयारी कार्य'),
        ),
        migrations.AlterField(
            model_name='isolationconstructionexependitureline',
            name='isolation_cons_expentiture_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.isolationconstructionexependiture'),
        ),
        migrations.AlterField(
            model_name='isolationmanagementdetailline',
            name='isolation_management_detail_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.isolationmanagementdetail'),
        ),
        migrations.AlterField(
            model_name='medicalreceiptline',
            name='medical_receipt_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.medicalreceipt'),
        ),
        migrations.AlterField(
            model_name='medicaluseline',
            name='medical_use_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.medicaluse'),
        ),
        migrations.AlterField(
            model_name='pcrtestcompliancedetailline',
            name='pcrtest_compliance_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.pcrtestcompliancedetail'),
        ),
        migrations.AlterField(
            model_name='rdttestdetailline',
            name='rdt_test_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.rdttestdetail'),
        ),
    ]
