# Generated by Django 3.1.4 on 2021-02-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_covid_hospital_detail_line_update_related_field'),
        ('forms', '0017_alter_districtcovidmanagement_blank'),
    ]

    operations = [
    ]
