# Generated by Django 3.1.4 on 2021-01-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0010_proince_district_local'),
        ('forms', '0018_alter_rdtline_alter_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundReceiptExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('fy_month_from', models.IntegerField(choices=[(1, 'वैशाख'), (2, 'जेष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'आश्विन'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फाल्गुण'), (12, 'चैत्र')], default=4)),
                ('fy_month_to', models.IntegerField(choices=[(1, 'वैशाख'), (2, 'जेष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'आश्विन'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फाल्गुण'), (12, 'चैत्र')], default=3)),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=25)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नाम')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_receipt_expenses', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष')),
                ('fiscal_year_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fre_fy_from', to='master_data.fiscalyear')),
                ('fiscal_year_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fre_fy_to', to='master_data.fiscalyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='medicalreceipt',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नाम'),
        ),
        migrations.AlterField(
            model_name='medicalreceipt',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_receipt', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष'),
        ),
        migrations.CreateModel(
            name='FundReceiptExpenseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('fy_start_received_amt', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fy_end_received_amt', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fy_start_expense_amt', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fy_end_expense_amt', models.DecimalField(decimal_places=2, max_digits=19)),
                ('budget_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.sourcebudget')),
                ('expense_header', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.expenseheader')),
                ('receipt_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.fundreceiptexpense')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
