# Generated by Django 3.1.4 on 2021-02-02 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_add_related_names_line_models_of_multiple_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disctrictquarantinemanagementline',
            name='quarantine_mgmgt_lines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dist_quarantine_lines', to='forms.districtcovidmanagement'),
        ),
        migrations.AlterField(
            model_name='districtisolationmanagementline',
            name='isolation_mgmt_lines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dist_isolation_lines', to='forms.districtcovidmanagement'),
        ),
        migrations.AlterField(
            model_name='districtlabtestline',
            name='lab_test_lines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dist_lab_lines', to='forms.districtcovidmanagement'),
        ),
    ]
