# Generated by Django 3.1.4 on 2021-02-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_alter_covidhospitalcollection_province_district_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexpenseline',
            name='date_imported',
            field=models.CharField(default='01/01/2077', max_length=15, verbose_name='आपूर्ति गरेको मिति'),
        ),
        migrations.AlterField(
            model_name='medicalexpenseline',
            name='date_to_import',
            field=models.CharField(default='01/01/2077', max_length=15, verbose_name='आपूर्ति गर्नुपर्ने मिति'),
        ),
        migrations.AlterField(
            model_name='medicalpurchasedescriptionline',
            name='date_procure_agreement',
            field=models.CharField(default='01/01/2077', max_length=15, verbose_name='खरिद सम्झौता मिति'),
        ),
        migrations.AlterField(
            model_name='medicalpurchasedescriptionline',
            name='date_received',
            field=models.CharField(default='01/01/2077', max_length=15, verbose_name='सामान प्राप्त मिति'),
        ),
    ]
