# Generated by Django 3.1.4 on 2021-02-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_merge_20210201_0530'),
        ('forms', '0019_alter_related_lines_in_lines_model_in_dist_isolation_dist_quarantine_dist_lab'),
    ]

    operations = [
    ]
