# Generated by Django 3.1.4 on 2021-01-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_add_fund_receipt_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcollection',
            name='fund_receipt_expense',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.fundreceiptexpense'),
        ),
    ]
