# Generated by Django 3.1.4 on 2021-01-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_remove_state_from_forms'),
        ('forms', '0020_alter_form_collections_add_fund_receipt_expense'),
    ]

    operations = [
    ]
