# Generated by Django 3.1.4 on 2021-02-03 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_alter_chief_minister_collection_add_action_implementation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinvestigationtracingline',
            name='case_investigation_tracing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.caseinvestigationtracing', verbose_name='केस अनुसन्धान ट्रेसिंग'),
        ),
    ]
