# Generated by Django 3.1.4 on 2021-01-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_auto_20210117_0659'),
        ('forms', '0021_merge_20210118_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'fund_receipt_expense'), (1, 'risk_allowance'), (2, 'medical_expense'), (3, 'medical_receipt'), (4, 'medical_use'), (5, 'pcr_test_compliance_detail'), (6, 'rdt_test_detail')], default=1),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpense',
            name='fiscal_year_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='fre_fy_from', to='master_data.fiscalyear', verbose_name='सुरु आर्थिक वर्ष'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpense',
            name='fiscal_year_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='fre_fy_to', to='master_data.fiscalyear', verbose_name='अन्त्य आर्थिक वर्ष'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpense',
            name='fy_month_from',
            field=models.IntegerField(choices=[(1, 'वैशाख'), (2, 'जेष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'आश्विन'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फाल्गुण'), (12, 'चैत्र')], default=4, verbose_name='सुरु महिना'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpense',
            name='fy_month_to',
            field=models.IntegerField(choices=[(1, 'वैशाख'), (2, 'जेष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'आश्विन'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फाल्गुण'), (12, 'चैत्र')], default=3, verbose_name='अन्त्य महिना'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpenseline',
            name='budget_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.sourcebudget', verbose_name='बजेट/आम्दानीको स्रोत'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpenseline',
            name='expense_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.expenseheader', verbose_name='खर्च शीर्षक'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpenseline',
            name='fy_end_expense_amt',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='अन्त्य महिनासम्म खर्च रकम'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpenseline',
            name='fy_end_received_amt',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='अन्त्य महिनासम्म प्राप्त रकम'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpenseline',
            name='fy_start_expense_amt',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='सुरुवात महिनासम्म खर्च रकम'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpenseline',
            name='fy_start_received_amt',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='सुरुवात महिनासम्म प्राप्त रकम'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpenseline',
            name='receipt_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.fundreceiptexpense', verbose_name=''),
        ),
    ]
