# Generated by Django 3.1.4 on 2021-01-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_auto_20210118_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcollection',
            name='cov_hos_equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.covidhospitalequipment'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='med_purchase_desc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.medicalpurchasedescription'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='pcr_kit_usage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.pcrkitusage'),
        ),
        migrations.AddField(
            model_name='formcollection',
            name='pcr_lab_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.pcrlaboratorydetail'),
        ),
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'fund_receipt_expense'), (1, 'risk_allowance'), (2, 'medical_expense'), (3, 'medical_receipt'), (4, 'medical_use'), (5, 'med_purchase_desc'), (6, 'pcr_test_compliance_detail'), (7, 'pcr_lab_detail'), (8, 'rdt_test_detail'), (9, 'pcr_kit_usage'), (11, 'cov_hos_equipment')], default=1),
        ),
    ]
