# Generated by Django 3.1.4 on 2021-02-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_alter_add_related_name_in_case_investigation_tracing_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinvestigationtracingoperationsline',
            name='caseinvestigationtracingoperations_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.caseinvestigationtracingoperations'),
        ),
    ]
