# Generated by Django 3.1.4 on 2021-01-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_auto_20210118_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'fund_receipt_expense'), (1, 'risk_allowance'), (2, 'medical_expense'), (3, 'medical_receipt'), (4, 'medical_use'), (5, 'med_purchase_desc'), (6, 'pcr_test_compliance_detail'), (7, 'pcr_lab_detail'), (8, 'rdt_test_detail'), (9, 'pcr_kit_usage')], default=1),
        ),
    ]
