# Generated by Django 3.1.4 on 2021-02-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_alter_add_related_name_in_relief_procure_dist_line'),
        ('forms', '0019_alter_covidhospitalcollection_province_district_fields'),
    ]

    operations = [
    ]
