# Generated by Django 3.1.4 on 2021-02-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20210203_0445'),
        ('forms', '0027_auto_20210205_0635'),
    ]

    operations = [
    ]
