# Generated by Django 3.1.4 on 2021-02-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_alter_provincecollection_provincefiscalyear'),
        ('forms', '0028_merge_20210205_0701'),
    ]

    operations = [
    ]
