# Generated by Django 3.1.4 on 2021-02-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_merge_20210208_0541'),
        ('forms', '0029_merge_20210208_0454'),
    ]

    operations = [
    ]
