# Generated by Django 3.1.4 on 2021-02-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_merge_20210208_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtisolationmanagementline',
            name='num_prepared_icu',
            field=models.IntegerField(null=True, verbose_name='तयारी अवस्थामा रहेको आई सी यु संख्या'),
        ),
    ]
