# Generated by Django 3.1.4 on 2021-02-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0030_merge_20210208_0952'),
        ('forms', '0030_auto_20210208_1559'),
    ]

    operations = [
    ]
