# Generated by Django 3.1.4 on 2021-02-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_merge_20210210_0541'),
        ('forms', '0031_merge_20210210_1204'),
    ]

    operations = [
    ]
