# Generated by Django 3.1.4 on 2021-02-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_merge_20210210_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundreceiptexpenseline',
            name='fy_end_expense_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='अन्त्य महिनासम्म खर्च रकम'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpenseline',
            name='fy_end_received_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='अन्त्य महिनासम्म प्राप्त रकम'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpenseline',
            name='fy_start_expense_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='सुरुवात महिनासम्म खर्च रकम'),
        ),
        migrations.AlterField(
            model_name='fundreceiptexpenseline',
            name='fy_start_received_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='सुरुवात महिनासम्म प्राप्त रकम'),
        ),
    ]
