# Generated by Django 3.1.4 on 2021-02-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_merge_20210216_0606'),
        ('forms', '0032_alter_fundreceiptexpense_blanksandnulls'),
    ]

    operations = [
    ]
