# Generated by Django 3.1.4 on 2021-02-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_alter_verbose_name_added_in_multiple_fields'),
        ('forms', '0032_alter_fundreceiptexpense_blanksandnulls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionplanimplementation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='actionplanimplementationline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='caseinvestigationtracing',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='caseinvestigationtracingline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='caseinvestigationtracingoperations',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='caseinvestigationtracingoperationsline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='covidhospitaldetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='covidhospitaldetailline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='covidhospitalequipment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='covidhospitalequipmentline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='covidhospitalmanagementchecklist',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='covidhospitalmanagementchecklistline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='covidhospitalmanpower',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='covidhospitalmanpowerline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='disctrictquarantinemanagementline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='districtcovidmanagement',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='districtisolationmanagementline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='districtlabtestline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='epidemicoutbreakpreparatorywork',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='epidemicoutbreakpreparatoryworkline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='fundoperation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='fundoperationline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='fundreceiptexpense',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='fundreceiptexpenseline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='isolationconstructionexependiture',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='isolationconstructionexependitureline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='isolationmanagementdetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='isolationmanagementdetailline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='medicalexpense',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='medicalexpenseline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='medicalpurchasedescription',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='medicalpurchasedescriptionline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='medicalreceipt',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='medicalreceiptline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='medicaluse',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='medicaluseline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pcrkitusage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pcrkitusageline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pcrlaboratorydetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pcrlaboratorydetailline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pcrtestcompliancedetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pcrtestcompliancedetailline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='provinceinstitutionmanagement',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='provinceinstitutionmanagementline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quarantineconstructionexpenditure',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quarantineconstructionexpenditureline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quarantinemanagementdetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quarantinemanagementdetailline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rdttestdetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rdttestdetailline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='receivedreliefdetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='receivedreliefdetailline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reliefdistributionexpense',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reliefdistributionexpenseline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reliefprocuredistribution',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reliefprocuredistributionline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reliefprocurementdetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reliefprocurementdetailline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='riskallowance',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='riskallowanceline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wardreliefprocuredistribution',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wardreliefprocuredistributionline',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='covidhospitalequipment',
            name='cov_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms_cov_hos', to='master_data.covidhospital', verbose_name='कोभिड डेडिकेटेड अस्पातालको नाम'),
        ),
        migrations.AlterField(
            model_name='covidhospitalmanpower',
            name='covidhospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.covidhospital', verbose_name='कोभिड डेडिकेटेड अस्पातालको नाम'),
        ),
        migrations.AlterField(
            model_name='medicalpurchasedescription',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_medPurchase_gov', to='master_data.governmentbody', verbose_name='निकायको नाम'),
        ),
        migrations.AlterField(
            model_name='medicalpurchasedescription',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_medPurchase_fy', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष'),
        ),
        migrations.AlterField(
            model_name='pcrtestcompliancedetail',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नाम'),
        ),
        migrations.AlterField(
            model_name='pcrtestcompliancedetail',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pctr_test_fiscal_year', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष'),
        ),
        migrations.AlterField(
            model_name='riskallowance',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody', verbose_name='निकायको नाम'),
        ),
        migrations.AlterField(
            model_name='riskallowance',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms_fre_fy_from', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष'),
        ),
    ]
