# Generated by Django 3.1.4 on 2021-02-25 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0033_dprexpense_dprexpenseline_quarterlyprogram_quarterlyprogramline_yearlytarget_yearlytargetline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherDesignationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_vacancy', models.IntegerField(verbose_name='शिक्षक दरबन्दी')),
                ('num_vacancy_filled', models.IntegerField(verbose_name='पदपूर्ति')),
                ('num_temp_filled', models.IntegerField(verbose_name='पदपूर्ति मध्ये करार')),
                ('num_student', models.IntegerField(verbose_name='विधार्थी संख्या')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='master_data.school', verbose_name='विधालयको नाम')),
                ('teacherdesignation_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.teacherdesignation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
