# Generated by Django 3.1.4 on 2021-02-24 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0033_dprexpense_dprexpenseline_quarterlyprogram_quarterlyprogramline_yearlytarget_yearlytargetline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedureGuideLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('text', models.TextField(verbose_name='विवरण')),
                ('act', models.CharField(max_length=300, verbose_name='ऐन ')),
                ('rules', models.CharField(max_length=300, verbose_name='नियमावली')),
                ('procedure_desc', models.CharField(max_length=300, verbose_name='कार्यविधि')),
                ('directory', models.CharField(max_length=300, verbose_name='निर्देशिका')),
                ('norms', models.CharField(max_length=300, verbose_name='नर्म्स')),
                ('total', models.FloatField(verbose_name='जम्मा')),
                ('procedure_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.procedureguide')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
