# Generated by Django 3.1.4 on 2021-02-21 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0010_add_designation_vacancy'),
        ('forms', '0033_dprexpense_dprexpenseline_quarterlyprogram_quarterlyprogramline_yearlytarget_yearlytargetline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesignationVacancyLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('total', models.PositiveIntegerField(verbose_name='जम्मा पदपूर्ति')),
                ('num_internal', models.PositiveIntegerField(verbose_name='आन्तरिक पदपूर्ति')),
                ('num_union', models.PositiveIntegerField(verbose_name='संख्या')),
                ('num_filled', models.PositiveIntegerField(verbose_name='साबिक स्थानीय निकायमा कार्यरत')),
                ('remaining_vacancy', models.PositiveIntegerField(verbose_name='रिक्त पद')),
                ('num_former_body', models.PositiveIntegerField(verbose_name='संघबाट समायोजन भई आएका')),
                ('remarks', models.CharField(blank=True, max_length=300, null=True, verbose_name='कैफियत')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_vacancy_lines', to='master_data.designation')),
                ('designation_vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.designationvacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
