# Generated by Django 3.1.4 on 2021-02-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0033_alter_verbose_name_added_in_multiple_fields'),
        ('forms', '0033_merge_20210217_0604'),
    ]

    operations = [
    ]
