# Generated by Django 3.1.4 on 2021-02-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0034_add_procedure_guide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedureguideline',
            old_name='text',
            new_name='desc',
        ),
    ]
