# Generated by Django 3.1.4 on 2021-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0034_merge_20210217_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundoperationline',
            name='body',
            field=models.CharField(max_length=300, null=True, verbose_name='उपलब्ध गराउने निकाय'),
        ),
    ]
