# Generated by Django 3.1.4 on 2021-02-22 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0034_service_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseMapConstruction',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseMapConstructionLine',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('application_count', models.IntegerField(
                    verbose_name='घरनक्शा पासको निवेदन संख्या')),
                ('temporary_permission', models.BooleanField(
                    default=False, verbose_name='अस्थायी अनुमति')),
                ('prev_year_approved_num', models.IntegerField(
                    verbose_name='कार्यसम्पन्न संख्या गत विगत वर्ष अनुमति लिएका मध्ये')),
                ('current_year_approved_num', models.IntegerField(
                    verbose_name='कार्यसम्पन्न संख्या यो वर्ष अनुमति लिएका मध्ये')),
                ('total', models.IntegerField(verbose_name='जम्मा')),
                ('remarks', models.CharField(max_length=300, verbose_name='कैफियत')),
                ('housemapconstruction_line', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.housemapconstruction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
