# Generated by Django 3.1.4 on 2021-02-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0034_add_revenue_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuedistributionline',
            name='remaining_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='पठाउन बाँकी रकम'),
        ),
    ]
