# Generated by Django 3.1.4 on 2021-02-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0035_alter_fundoperationline_bodycharfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceinstitutionmanagementline',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.committee', verbose_name='प्रदेश तहमा गठन भएका समितिको नाम'),
        ),
        migrations.AlterField(
            model_name='provinceinstitutionmanagementline',
            name='province_institution_management',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.provinceinstitutionmanagement', verbose_name='संस्थागत व्यवस्था'),
        ),
    ]
