# Generated by Django 3.1.4 on 2021-02-22 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0035_add_contract_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecoverAmountLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('income_name', models.CharField(max_length=500, verbose_name='आयको नाम')),
                ('prev_year_rem_amt', models.FloatField(verbose_name='गत बर्षसम्मको बाँकी')),
                ('this_year_recover_amt', models.FloatField(verbose_name='यस बर्षको बाँकी')),
                ('cur_rem_amt', models.FloatField(verbose_name='बाँकी')),
                ('rem_recover_amt', models.FloatField(verbose_name='यस बर्ष असुली')),
                ('total_rem_amt', models.FloatField(verbose_name='जम्मा बाँकी')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recover_amount_lines', to='master_data.contractor', verbose_name='ठेकेदारको नाम')),
                ('recover_amount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.recoveramount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
