# Generated by Django 3.1.4 on 2021-02-25 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0035_change_name_text_to_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureExceedingAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenditureExceedingAllocationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('title', models.CharField(max_length=300, verbose_name='शीर्षक')),
                ('appropriated_amt', models.FloatField(verbose_name='विनियोजित रकम')),
                ('expense_amt', models.FloatField(verbose_name='खर्च भएको रकम')),
                ('expense_exceeded_amt', models.FloatField(verbose_name='बढी खर्च भएको रकम')),
                ('expenditure_exceeding_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.expenditureexceedingallocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
