# Generated by Django 3.1.4 on 2021-02-26 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_merge_20210225_1023'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0035_change_field_text_remaining_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatePartnershipProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatePartnershipProgramLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('num_project', models.PositiveIntegerField(verbose_name='आयोजनाको संख्या')),
                ('budget_amt', models.FloatField(verbose_name='बजेट रकम')),
                ('spent_amount', models.FloatField(verbose_name='खर्च रकम')),
                ('financial_progress_percentage', models.FloatField(verbose_name='वित्तीय प्रगति प्रतिशत')),
                ('physical_progress_percentage', models.FloatField(verbose_name='भौतिक प्रगति प्रतिशत')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_partnership_programs', to='master_data.projecttype', verbose_name='आयोजनाको प्रकार')),
                ('state_partnership_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.statepartnershipprogram')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
