# Generated by Django 3.1.4 on 2021-02-19 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('forms', '0036_alter_provinceinstitutionmanagement_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefdistributionexpense',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reliefdistribution', to='master_data.governmentbody', verbose_name='निकायको नाम'),
        ),
        migrations.AlterField(
            model_name='reliefdistributionexpense',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reliefdistribution', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष'),
        ),
    ]
