# Generated by Django 3.1.4 on 2021-02-25 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0036_add_expenditure_exceeding_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectoralBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectoralBudgetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('main_area', models.CharField(max_length=300, verbose_name='मुख्य क्षेत्र')),
                ('yearly_budget', models.FloatField(verbose_name='वार्षिक वजेट')),
                ('expensed_amount', models.FloatField(verbose_name='खर्च रकम')),
                ('percentage_of_total_expenditure', models.FloatField(verbose_name='कुल खर्च मध्ये प्रतिशत')),
                ('sectoral_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.sectoralbudget')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
