# Generated by Django 3.1.4 on 2021-02-26 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0036_add_state_partnership_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPartnershipProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalPartnershipProgramLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('project_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='आयोजनाको नाम')),
                ('cost_estimation', models.FloatField(verbose_name='लागत अनुमान')),
                ('programme_amount', models.FloatField(verbose_name='कार्यक्रमबाट')),
                ('local_level_amount', models.FloatField(verbose_name='स्थानीय तहबाट')),
                ('other_amount', models.FloatField(verbose_name='गैसस वा अन्य')),
                ('public_participation_amount', models.FloatField(verbose_name='लागत सहभागितबाट व्यहोरिने रकम')),
                ('total_amount', models.FloatField(verbose_name='जम्मा')),
                ('project_completed_amount', models.FloatField(blank=True, null=True, verbose_name='कार्य सम्पन्न रकम')),
                ('concerned_member_name', models.CharField(max_length=300, verbose_name='सम्बन्धीत सभासदको नाम')),
                ('local_partnership_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.localpartnershipprogram')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_partnership_programs', to='master_data.projecttype', verbose_name='आयोजनाको प्रकार')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
