# Generated by Django 3.1.4 on 2021-02-28 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0037_financialstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSubmitApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetSubmitApprovalLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('desc', models.CharField(max_length=300, verbose_name='विवरण')),
                ('date', models.CharField(max_length=300, verbose_name='मिति र रकम')),
                ('total_budget', models.CharField(max_length=300, verbose_name='कुल बजेट')),
                ('amount', models.FloatField(verbose_name='रकम')),
                ('budgetsubmitapproval_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.budgetsubmitapproval')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
