# Generated by Django 3.1.4 on 2021-02-25 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0020_merge_20210224_1035'),
        ('forms', '0037_add_sectoral_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForeignTripLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('name', models.CharField(max_length=300, verbose_name='बैदेशिक भ्रमणमा जानेको पद र नाम ')),
                ('payment_amount', models.FloatField(verbose_name='भुक्तानी रकम')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_trip_line', to='master_data.country', verbose_name='भ्रमण गरेको देश')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.designation', verbose_name='')),
                ('foreign_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.foreigntrip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
