# Generated by Django 3.1.4 on 2021-02-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0037_add_expense_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensedescline',
            old_name='official_expsense',
            new_name='official_expense',
        ),
    ]
