# Generated by Django 3.1.4 on 2021-03-01 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('forms', '0038_auto_20210301_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundreceiptexpense',
            name='fiscal_year',
            field=models.ForeignKey(default=106.3157894736842, on_delete=django.db.models.deletion.PROTECT, related_name='fund_receipt_expenses', to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष'),
            preserve_default=False,
        ),
    ]
