# Generated by Django 3.1.4 on 2021-03-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0038_bugetsubmitapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatementresponsibilityline',
            name='deadline',
            field=models.DateField(null=True, verbose_name='गतको बर्षको अन्तिम मौदात'),
        ),
        migrations.AlterField(
            model_name='financialstatementresponsibilityline',
            name='start_date',
            field=models.DateField(null=True, verbose_name='यस बर्षको सुरु मौदात'),
        ),
    ]
