# Generated by Django 3.1.4 on 2021-02-23 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0038_chnage_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegralAdvancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegralAdvancementLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('desc', models.TextField(verbose_name='विवरण')),
                ('remaining_advance', models.FloatField(verbose_name='यस बर्ष फछ्यौंट')),
                ('cancelled_amount', models.FloatField(verbose_name='गत बर्षको पेश्की बाँकी')),
                ('remaining_amount', models.FloatField(verbose_name='गत बर्षको बाँकी')),
                ('added_amount', models.FloatField(verbose_name='यस बर्षको थप')),
                ('total', models.FloatField(verbose_name='जम्मा')),
                ('integral_advancement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.integraladvancement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
