# Generated by Django 3.1.4 on 2021-02-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_add_null_true_blank_true_designation_field'),
        ('forms', '0038_add_foreign_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigntripline',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.designation', verbose_name=''),
        ),
    ]
