# Generated by Django 3.1.4 on 2021-02-25 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_add_null_true_blank_true_designation_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0039_add_null_true_blank_true_designation_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenditureDetailLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('received_amount', models.FloatField(verbose_name='प्राप्त रकम')),
                ('expensed_amount', models.FloatField(verbose_name='खर्च रकम')),
                ('remaining_amount', models.FloatField(verbose_name='बाँकी रकम')),
                ('expenditure_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.expendituredetail')),
                ('grant_providing_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditure_detail_line', to='master_data.governmentbody', verbose_name='अनुदान प्रदान गर्ने निकाय')),
                ('grant_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditure_detail_lines', to='master_data.granttype', verbose_name='अनुदानको प्रकार')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
