# Generated by Django 3.1.4 on 2021-03-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0040_add_expenditure_detail'),
        ('forms', '0039_auto_20210301_1600'),
        ('forms', '0039_add_integral_advanced'),
        ('forms', '0037_add_local_partnership_program'),
        ('forms', '0038_add_foreign_trip'),
        ('forms', '0038_conditionalgrant'),
    ]

    operations = [
    ]
