# Generated by Django 3.1.4 on 2021-03-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0041_merge_20210303_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalconvenience',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='additionalconvenienceline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='budgetsubmitapproval',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='budgetsubmitapprovalline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='conditionalgrant',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='conditionalgrantline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='consumercommitteeconstructiondescription',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='consumercommitteeconstructiondescriptionline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractdesc',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contractdescline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='designationvacancy',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='designationvacancyline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dprexpense',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dprexpenseline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='expendituredetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='expendituredetailline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='expenditureexceedingallocation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='expenditureexceedingallocationline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='expensedesc',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='expensedescline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='financialstatement',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='financialstatementbankaccountreconciledline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='financialstatementdeductamountline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='financialstatementresponsibilityline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='foreigntrip',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='foreigntripline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='grantreturnline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='housemapconstruction',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='housemapconstructionline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='incompleteconstructionwork',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='incompleteconstructionworkline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='integraladvancement',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='integraladvancementline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='judicialcommittee',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='judicialcommitteeline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='localpartnershipprogram',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='localpartnershipprogramline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='procedureguide',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='procedureguideline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='procurementauditor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='procurementauditorline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quarterlyprogram',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quarterlyprogramline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='recoveramount',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='recoveramountline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='remainingadvanceline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='revenuedistributedline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='revenuedistribution',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='revenuedistributionline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sectoralbudget',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sectoralbudgetline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='serviceflow',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='serviceflowline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='statepartnershipprogram',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='statepartnershipprogramline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='teacherdesignation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='teacherdesignationline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='vehiclepurchase',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='vehiclepurchaseline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='yearlytarget',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='yearlytargetline',
            options={'ordering': ['id']},
        ),
    ]
