# Generated by Django 3.1.4 on 2021-03-10 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('forms', '0042_auto_20210303_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainingadvanceline',
            name='remaining_advance',
            field=models.CharField(max_length=300, verbose_name='पेश्की बाँकी '),
        ),
        migrations.AlterField(
            model_name='vehiclepurchaseline',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.governmentbody', verbose_name='प्रयोग गर्नेपदाधिकारी र्सस्था'),
        ),
    ]
