# Generated by Django 3.1.4 on 2021-03-15 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0002_recommend_training_center'),
        ('forms', '0042_auto_20210303_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailToEmployer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotifyEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PMEmploymentExpense',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendTrainingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisteredUnemployment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisteredUnemploymentLine',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('unemployed_registered_num', models.IntegerField(
                    verbose_name='दर्ता गरिएका बेरोजगार संख्या')),
                ('employed_registered_num', models.IntegerField(
                    verbose_name='दर्ता भएको मध्येबाट रोजगारी प्रधान गरीएको संख्या ')),
                ('employment_provided_total_days',
                 models.IntegerField(verbose_name='जम्मा दिन')),
                ('employment_provided_days_per_person',
                 models.IntegerField(verbose_name='प्रति व्यक्ति दिन')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष')),
                ('reg_unemployment_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                            related_name='lines', to='forms.registeredunemployment')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendTrainingCenterLine',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('training_subject', models.CharField(
                    max_length=300, verbose_name='तालिमको विषय')),
                ('total_recommend', models.IntegerField(
                    verbose_name='सिफारिस गरेको व्यक्ति संख्या')),
                ('num_employed', models.IntegerField(
                    verbose_name='रोजगारी प्राप्त गर्ने व्यक्ति संख्या')),
                ('employed_days', models.IntegerField(
                    verbose_name='रोजगारी प्राप्त दिन')),
                ('ecommendtrainingcenter_line', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.recommendtrainingcenter')),
                ('training_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      to='master_data.trainingcenter', verbose_name='तालिम केन्द्रको नाम')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PMEmploymentExpenseLine',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('budget', models.FloatField(verbose_name='बजेट रु.')),
                ('expense', models.FloatField(verbose_name='खर्च रु.')),
                ('worker_wage', models.FloatField(
                    verbose_name='श्रमिक ज्याला खर्च रु.')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष')),
                ('pm_employment_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                         related_name='lines', to='forms.pmemploymentexpense')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotifyEmployeeLine',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('employer_name_address', models.CharField(
                    blank=True, max_length=250, null=True, verbose_name='रोजगारदाताको नाम ठेगाना ')),
                ('num_workers_provided', models.IntegerField(
                    verbose_name='उपलव्ध गराएको श्रमिक संख्या ')),
                ('employment_provided_total_days',
                 models.IntegerField(verbose_name='जम्मा दिन')),
                ('employment_provided_days_per_person',
                 models.IntegerField(verbose_name='प्रतिव्यक्ति दिन ')),
                ('employer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    to='master_data.employertype', verbose_name='रोजगारदाताको किसिम (सार्वजनिक आयोजन, निजी क्षेत्र, गैसस)')),
                ('notify_employee_line', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.notifyemployee')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentAssessmentLine',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('available_employment', models.IntegerField(
                    verbose_name='उपलव्ध हुन सक्ने रोजगारीको (संख्यामा)')),
                ('employment_sector', models.CharField(blank=True, max_length=250,
                                                       null=True, verbose_name='रोजगारीका सम्भावित क्षेत्रहरु')),
                ('emp_assessment_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                          related_name='lines', to='forms.employmentassessment')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='master_data.fiscalyear', verbose_name='आर्थिक बर्ष')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailToEmployerLine',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(
                    auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(
                    auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('employer_name_address', models.CharField(
                    blank=True, max_length=250, null=True, verbose_name='रोजगारदाताको नाम ठेगाना ')),
                ('employer_notified_date', models.DateField(null=True)),
                ('detail_to_emp_line', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.detailtoemployer')),
                ('employer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    to='master_data.employertype', verbose_name='रोजगारदाताको किसिम (सार्वजनिक आयोजन, निजी क्षेत्र, गैसस)')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
