# Generated by Django 3.1.4 on 2021-03-14 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0043_detailtoemployer_detailtoemployerline_employmentassessment_employmentassessmentline_notifyemployee_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOperativeExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('amt_operational_expenses', models.FloatField(verbose_name='संचालन खर्च रु. ')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminOperativeExpenseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('designation', models.CharField(max_length=255, verbose_name='पद')),
                ('monthly_salary_expense', models.FloatField(verbose_name='मासिक तलब खर्च रु. ')),
                ('total_expense_pre_previous_fy', models.FloatField(verbose_name='जम्मा खर्च रु. २०७५ /७६ ')),
                ('total_expense_previous_fy', models.FloatField(verbose_name='जम्मा खर्च रु. २०७६ /७७ ')),
                ('total_expense_current_fy', models.FloatField(verbose_name='जम्मा खर्च रु. २०७७ /७८ ')),
                ('admin_op_expense_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='forms.adminoperativeexpense')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
