# Generated by Django 3.1.4 on 2021-03-15 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0002_recommend_training_center'),
        ('forms', '0043_recommend_training_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryFinancialIncentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryFinancialIncentiveLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('total_job_opening', models.IntegerField(verbose_name='माग भएको प्रशिक्षार्थी श्रमिक संख्या')),
                ('financial_incentive_amount', models.FloatField(verbose_name='यो वर्ष सम्मको खर्च')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.fiscalyear', verbose_name='आर्थिक वर्ष')),
                ('industry_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.industry', verbose_name='उधोग प्रतिष्ठानको नाम')),
                ('industryfinancialincentive_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.industryfinancialincentive')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
