# Generated by Django 3.1.4 on 2021-03-15 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0002_recommend_training_center'),
        ('forms', '0044_industry_financial_incentive'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAssistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialAssistanceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('foreign_employment_board_received_amount', models.FloatField(verbose_name='वैदेशिक रोजगार बोर्डबाट प्राप्त रु.')),
                ('concerned_distribution_amount', models.FloatField(verbose_name='सम्बन्धीतलाइ वितरण रु.')),
                ('financialassistance_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.financialassistance')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.fiscalyear', verbose_name='आर्थिक वर्ष')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
