# Generated by Django 3.1.4 on 2021-03-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0045_contactdetails_contactdetailsline_meetingdetail_meetingdetailline_programmonitoring_programmonitorin'),
        ('forms', '0043_auto_20210310_1615'),
    ]

    operations = [
    ]
