# Generated by Django 3.1.4 on 2021-03-15 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0046_subsistenceallowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashForWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashForWorkLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='सिर्जना मिति')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('formulated_plans', models.TextField(verbose_name='तर्जुमा गरेको योजनाहरु')),
                ('estimated_cost', models.FloatField(verbose_name='लागत अनुमान रु.')),
                ('is_included', models.BooleanField(verbose_name='वार्षिक नीति तथा कार्यक्रममा समावेश भएको छ / छैन')),
                ('estimated_num_jobs', models.IntegerField(verbose_name='उपलव्ध हुने अनुमानीत रोजगारी संख्या')),
                ('jobs_pre_previous_fy', models.IntegerField(verbose_name='हालसम्म उपलव्ध भएको रोजगारी संख्या २०७५ /७६')),
                ('jobs_previous_fy', models.IntegerField(verbose_name='हालसम्म उपलव्ध भएको रोजगारी संख्या २०७६ /७७')),
                ('jobs_current_fy', models.IntegerField(verbose_name='हालसम्म उपलव्ध भएको रोजगारी संख्या २०७७ /७८')),
                ('expense_jobs_pre_previous_fy', models.FloatField(verbose_name='रोजगारी प्रधान गरीएको खर्च रु २०७५ /७६')),
                ('expense_jobs_previous_fy', models.FloatField(verbose_name='रोजगारी प्रधान गरीएको खर्च रु २०७६ /७७')),
                ('expense_jobs_current_fy', models.FloatField(verbose_name='रोजगारी प्रधान गरीएको खर्च रु २०७७ /७८')),
                ('cashforwork_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.cashforwork')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
