# Generated by Django 3.1.4 on 2021-03-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0048_recomded_traningcenter_and_subasistence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashforworkline',
            name='cashforwork_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.cashforwork'),
        ),
        migrations.AlterField(
            model_name='financialassistanceline',
            name='financialassistance_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.financialassistance'),
        ),
        migrations.AlterField(
            model_name='industryfinancialincentiveline',
            name='industryfinancialincentive_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.industryfinancialincentive'),
        ),
        migrations.AlterField(
            model_name='recommendtrainingcenterline',
            name='ecommendtrainingcenter_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.recommendtrainingcenter'),
        ),
        migrations.AlterField(
            model_name='subsistenceallowanceline',
            name='subsistenceallowance_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forms.subsistenceallowance'),
        ),
    ]
