from .medical_expense import *
from .risk_allowance import *
from .medical_receipt import *
from .medical_use import *
from .pcr_test_compliance_detail import *
from .rdttestdetail import *
from .med_purchase_desc import *
from .pcr_lab_detail import *
from .pcr_kit_usage import *
from .covid_hos_equip import *
from .fund_receipt_expense import *
from .epidemic_outbreak_preparatory_work import *
from .action_plan_implementation import *
from .case_investigation_tracing import *
from .province_institution_management import *
from .covid_hospital_manpower import *
from .covidhospitaldetail import *
from .isolationmanagementdetail import *
from .isolationconstructionexpenditure import *
from .districtcovidmanagement import *
from .quarantine_management_detail import *
from .quarantine_construct_expenditure import *
from .cov_hos_management_checklist import *
from .fund_operation import *
from .ward_relief_procure_distribution import *
from .received_relief_detail import *
from .relief_distribution_expense import *
from .districtcovidmanagement import *
from .case_inve_trac_operations import *
from .reliefprocuredistribution import *
from .reliefprocurementdetail import *
from .procurement_auditor import *
from .incomplete_construction_work import *
from .quarterly_program import *
from .drp_expense import *
from .yearly_target import *
from .revenue_distribution import *
from .state_partnership_program import *
from .local_partnership_program import *
from .designation_vacancy import *
from .contract_desc import *
from .recover_amount import *
from .expense_desc import *
from .integral_advancement import *
