# Generated by Django 3.1.4 on 2021-01-27 06:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0003_auto_20210127_1223'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormCollection',
            new_name='CovHosFormCollection',
        ),
    ]
