# Generated by Django 3.1.4 on 2021-01-28 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_merge_20210128_1056'),
        ('collection', '0003_provinceformcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinceformcollection',
            name='district_covid_management',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.districtcovidmanagement'),
        ),
    ]
