# Generated by Django 3.1.4 on 2021-01-28 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_merge_20210128_1056'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0004_provinceformcollection_district_covid_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceformcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'epidemic_outbreak_prep'), (1, 'fund_receipt_expense'), (2, 'risk_allowance'), (3, 'medical_expense'), (4, 'medical_receipt'), (5, 'medical_use'), (6, 'med_purchase_desc'), (7, 'pcr_test_compliance_detail'), (8, 'pcr_lab_detail'), (9, 'rdt_test_detail'), (10, 'pcr_kit_usage'), (11, 'covid_hos_mainpower'), (12, 'cov_hos_equipment'), (13, 'covid_hospital_detail'), (14, 'quarantine_management_detail'), (15, 'isolation_management_detail'), (16, 'quarantine_contruction_expenditure'), (17, 'isolation_construction_expenditure'), (18, 'district_covid_management')], default=0),
        ),
        migrations.CreateModel(
            name='InternalAffairFormCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(blank=True, choices=[(0, 'epidemic_outbreak_prep'), (1, 'fund_receipt_expense'), (2, 'risk_allowance'), (3, 'medical_expense'), (4, 'medical_receipt'), (5, 'medical_use'), (6, 'med_purchase_desc'), (7, 'pcr_test_compliance_detail'), (8, 'pcr_lab_detail'), (9, 'rdt_test_detail'), (10, 'pcr_kit_usage'), (11, 'covid_hos_mainpower'), (12, 'cov_hos_equipment'), (13, 'covid_hospital_detail'), (14, 'quarantine_management_detail'), (15, 'isolation_management_detail'), (16, 'quarantine_contruction_expenditure'), (17, 'isolation_construction_expenditure'), (18, 'district_covid_management')], default=0)),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('incomplete', 'INCOMPLETE'), ('submitted', 'SUBMITTED'), ('completed', 'COMPLETED')], default='started', max_length=20)),
                ('action_plan_implementation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.actionplanimplementation')),
                ('epidemic_outbreak_prep', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.epidemicoutbreakpreparatorywork')),
                ('fund_receipt_expense', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.fundreceiptexpense')),
                ('risk_allowance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.riskallowance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
