# Generated by Django 3.1.4 on 2021-01-28 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20210128_1456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0005_auto_20210128_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalaffairformcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'epidemic_outbreak_prep'), (1, 'fund_receipt_expense'), (2, 'risk_allowance'), (3, 'action_plan_implementation')], default=0),
        ),
        migrations.CreateModel(
            name='ChiefMinisterOfficeFormCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(blank=True, choices=[(0, 'epidemic_outbreak_prep'), (1, 'fund_receipt_expense'), (2, 'risk_allowance'), (3, 'province_institute_management')], default=0)),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('incomplete', 'INCOMPLETE'), ('submitted', 'SUBMITTED'), ('completed', 'COMPLETED')], default='started', max_length=20)),
                ('epidemic_outbreak_prep', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.epidemicoutbreakpreparatorywork')),
                ('fund_receipt_expense', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.fundreceiptexpense')),
                ('province_institute_management', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.provinceinstitutionmanagement')),
                ('risk_allowance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.riskallowance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
