# Generated by Django 3.1.4 on 2021-01-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_merge_20210129_1055'),
        ('collection', '0006_auto_20210128_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinceformcollection',
            name='fund_operation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.fundoperation'),
        ),
        migrations.AlterField(
            model_name='provinceformcollection',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'epidemic_outbreak_prep'), (1, 'fund_receipt_expense'), (2, 'risk_allowance'), (3, 'medical_expense'), (4, 'medical_receipt'), (5, 'medical_use'), (6, 'med_purchase_desc'), (7, 'pcr_test_compliance_detail'), (8, 'pcr_lab_detail'), (9, 'rdt_test_detail'), (10, 'pcr_kit_usage'), (11, 'covid_hos_mainpower'), (12, 'cov_hos_equipment'), (13, 'covid_hospital_detail'), (14, 'quarantine_management_detail'), (15, 'isolation_management_detail'), (16, 'quarantine_contruction_expenditure'), (17, 'isolation_construction_expenditure'), (18, 'district_covid_management'), (19, 'fund_operation')], default=0),
        ),
    ]
