# Generated by Django 3.1.4 on 2021-01-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20210128_0833'),
        ('collection', '0007_auto_20210129_1055'),
    ]

    operations = [
    ]
