# Generated by Django 3.1.4 on 2021-01-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20210129_1432'),
        ('collection', '0009_alter_hospital_body_inheritaddress'),
    ]

    operations = [
    ]
