# Generated by Django 3.1.4 on 2021-02-02 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('collection', '0012_merge_20210129_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='covhosformcollection',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.district'),
        ),
        migrations.AddField(
            model_name='covhosformcollection',
            name='local_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.locallevel'),
        ),
        migrations.AddField(
            model_name='covhosformcollection',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.province'),
        ),
        migrations.AlterField(
            model_name='covhosformcollection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
