# Generated by Django 3.1.4 on 2021-02-01 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0012_merge_20210129_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='covhosformcollection',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
