# Generated by Django 3.1.4 on 2021-02-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('collection', '0013_alter_covidhospitalcollection_province_district_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='covhosformcollection',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.covidhospital'),
        ),
    ]
