# Generated by Django 3.1.4 on 2021-02-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_auto_20210202_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='covhosformcollection',
            name='reject_msg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
