# Generated by Django 3.1.4 on 2021-02-03 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('collection', '0014_alter_covidhospitalcollection_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='covhosformcollection',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody'),
        ),
    ]
