# Generated by Django 3.1.4 on 2021-02-05 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0015_auto_20210205_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinceformcollection',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provinceformcollection',
            name='reject_msg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
