# Generated by Django 3.1.4 on 2021-02-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_alter_covidhospitalcollection_fiscalyear'),
        ('collection', '0014_auto_20210202_1257'),
    ]

    operations = [
    ]
