# Generated by Django 3.1.4 on 2021-02-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_auto_20210204_1150'),
        ('collection', '0016_auto_20210205_0536'),
        ('collection', '0015_covhosformcollection_reject_msg'),
        ('collection', '0018_auto_20210205_0635'),
    ]

    operations = [
    ]
