# Generated by Django 3.1.4 on 2021-02-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('collection', '0019_alter_chiefministercollection_provincefiscalyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='locallevelformcollection',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody'),
        ),
        migrations.AddField(
            model_name='locallevelformcollection',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.district'),
        ),
        migrations.AddField(
            model_name='locallevelformcollection',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.fiscalyear'),
        ),
        migrations.AddField(
            model_name='locallevelformcollection',
            name='local_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.locallevel'),
        ),
        migrations.AddField(
            model_name='locallevelformcollection',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.province'),
        ),
    ]
