# Generated by Django 3.1.4 on 2021-02-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0019_merge_20210205_0701'),
        ('collection', '0020_alter_locallevelcollection_initalformfields'),
    ]

    operations = [
    ]
