# Generated by Django 3.1.4 on 2021-02-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0021_merge_20210208_0454'),
        ('collection', '0021_merge_20210208_0541'),
    ]

    operations = [
    ]
