# Generated by Django 3.1.4 on 2021-03-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0022_merge_20210208_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefministerofficeformcollection',
            name='status',
            field=models.CharField(choices=[('started', 'STARTED'), ('incomplete', 'INCOMPLETE'), ('completed', 'COMPLETED'), ('submitted', 'SUBMITTED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='covhosformcollection',
            name='status',
            field=models.CharField(choices=[('started', 'STARTED'), ('incomplete', 'INCOMPLETE'), ('completed', 'COMPLETED'), ('submitted', 'SUBMITTED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='internalaffairformcollection',
            name='status',
            field=models.CharField(choices=[('started', 'STARTED'), ('incomplete', 'INCOMPLETE'), ('completed', 'COMPLETED'), ('submitted', 'SUBMITTED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='locallevelformcollection',
            name='status',
            field=models.CharField(choices=[('started', 'STARTED'), ('incomplete', 'INCOMPLETE'), ('completed', 'COMPLETED'), ('submitted', 'SUBMITTED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='provinceformcollection',
            name='status',
            field=models.CharField(choices=[('started', 'STARTED'), ('incomplete', 'INCOMPLETE'), ('completed', 'COMPLETED'), ('submitted', 'SUBMITTED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='started', max_length=20),
        ),
    ]
