# Generated by Django 3.1.4 on 2021-03-01 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_auto_20210219_0618'),
        ('collection', '0023_auto_20210301_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalaffairformcollection',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.fiscalyear'),
        ),
    ]
