# Generated by Django 3.1.4 on 2021-03-01 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('collection', '0024_auto_20210301_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalaffairformcollection',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.fiscalyear'),
        ),
    ]
