# Generated by Django 3.1.4 on 2021-03-05 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0001_initial'),
        ('forms', '0042_auto_20210303_0635'),
        ('collection', '0025_auto_20210301_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSixFormCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(blank=True, choices=[(0, 'procurement_auditor'), (1, 'incomplete_construction_work'), (2, 'quarterly_program'), (3, 'dpr_expense'), (4, 'yearly_target'), (5, 'service_flow'), (6, 'house_map_construction'), (7, 'vehicle_purchase'), (8, 'additional_convenience'), (9, 'conditional_grant'), (10, 'designation_vacancy'), (11, 'contract_desc'), (12, 'recover_amount'), (13, 'expense_desc'), (14, 'integral_advancement'), (15, 'teacher_designation'), (16, 'judicial_committee'), (17, 'consumer_committee_construction_description'), (18, 'financial_statement'), (19, 'budget_submit_approval'), (20, 'procedure_guide'), (21, 'expenditure_exceeding_allocation'), (22, 'sectoral_budget'), (23, 'foreign_trip'), (24, 'expenditure_detail'), (25, 'revenue_distribution'), (26, 'state_partnership_program')], default=0)),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('incomplete', 'INCOMPLETE'), ('completed', 'COMPLETED'), ('submitted', 'SUBMITTED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='started', max_length=20)),
                ('reject_msg', models.CharField(blank=True, max_length=250, null=True)),
                ('additional_convenience', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.additionalconvenience')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectin_six_approver_user', to=settings.AUTH_USER_MODEL)),
                ('body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.governmentbody')),
                ('budget_submit_approval', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.budgetsubmitapproval')),
                ('conditional_grant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.conditionalgrant')),
                ('consumer_committee_construction_description', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.consumercommitteeconstructiondescription')),
                ('contract_desc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.contractdesc')),
                ('designation_vacancy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.designationvacancy')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.district')),
                ('dpr_expense', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.dprexpense')),
                ('expenditure_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.expendituredetail')),
                ('expenditure_exceeding_allocation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.expenditureexceedingallocation')),
                ('expense_desc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.expensedesc')),
                ('financial_statement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.financialstatement')),
                ('fiscal_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.fiscalyear')),
                ('foreign_trip', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.foreigntrip')),
                ('house_map_construction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.housemapconstruction')),
                ('incomplete_construction_work', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.incompleteconstructionwork')),
                ('integral_advancement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.integraladvancement')),
                ('judicial_committee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.judicialcommittee')),
                ('local_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.locallevel')),
                ('procedure_guide', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.procedureguide')),
                ('procurement_auditor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.procurementauditor')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.province')),
                ('quarterly_program', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.quarterlyprogram')),
                ('recover_amount', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.recoveramount')),
                ('revenue_distribution', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.revenuedistribution')),
                ('sectoral_budget', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.sectoralbudget')),
                ('service_flow', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.serviceflow')),
                ('state_partnership_program', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.statepartnershipprogram')),
                ('teacher_designation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.teacherdesignation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_purchase', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.vehiclepurchase')),
                ('yearly_target', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.yearlytarget')),
            ],
        ),
    ]
