# Generated by Django 3.1.4 on 2020-12-27 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_governmentbody_governmentbodytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LocalLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master_data.address')),
                ('name', models.CharField(max_length=300)),
                ('date_establishment', models.DateField()),
            ],
            bases=('master_data.address',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master_data.address')),
                ('name', models.CharField(max_length=300)),
            ],
            bases=('master_data.address',),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='local_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.locallevel'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.country'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.district'),
        ),
        migrations.AddField(
            model_name='address',
            name='local_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.locallevel'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.province'),
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master_data.company')),
            ],
            bases=('master_data.company',),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master_data.company')),
            ],
            bases=('master_data.company',),
        ),
        migrations.CreateModel(
            name='IsolationCenter',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master_data.location')),
            ],
            bases=('master_data.location',),
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master_data.company')),
                ('capacity_daily_test', models.IntegerField()),
            ],
            bases=('master_data.company',),
        ),
        migrations.CreateModel(
            name='QuanrantineCenter',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master_data.location')),
            ],
            bases=('master_data.location',),
        ),
    ]
