# Generated by Django 3.1.4 on 2020-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_add_fy'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='date_end_bs',
            field=models.CharField(default='2000/01/01', max_length=15, verbose_name='अन्त्य मिति'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='date_start_bs',
            field=models.CharField(default='2000/01/01', max_length=15, verbose_name='सुरू मिति'),
        ),
    ]
