# Generated by Django 3.1.4 on 2021-01-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='capacity_daily_test',
            field=models.IntegerField(default=0),
        ),
    ]
