# Generated by Django 3.1.4 on 2021-01-28 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_laboratory_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpower',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manpower',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
