# Generated by Django 3.1.4 on 2020-12-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_change_fy_bs_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='date_end_bs',
            field=models.CharField(default='01/01/2000', max_length=15, verbose_name='अन्त्य मिति'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='date_start_bs',
            field=models.CharField(default='01/01/2000', max_length=15, verbose_name='सुरू मिति'),
        ),
    ]
