# Generated by Django 3.1.4 on 2021-01-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_alter_manpower_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidhospital',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.country'),
        ),
        migrations.AddField(
            model_name='covidhospital',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.district'),
        ),
        migrations.AddField(
            model_name='covidhospital',
            name='local_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.locallevel'),
        ),
        migrations.AddField(
            model_name='covidhospital',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.province'),
        ),
        migrations.AddField(
            model_name='covidhospital',
            name='ward',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='governmentbody',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.country'),
        ),
        migrations.AddField(
            model_name='governmentbody',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.district'),
        ),
        migrations.AddField(
            model_name='governmentbody',
            name='local_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.locallevel'),
        ),
        migrations.AddField(
            model_name='governmentbody',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.province'),
        ),
        migrations.AddField(
            model_name='governmentbody',
            name='ward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
