# Generated by Django 3.1.4 on 2020-12-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_product_unitofmeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='नाम'),
        ),
    ]
