# Generated by Django 3.1.4 on 2020-12-24 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_change_uom_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='नाम')),
            ],
        ),
        migrations.CreateModel(
            name='CovidHospital',
            fields=[
                ('hospital_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master_data.hospital')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255, verbose_name='वर्णन')),
                ('date_announcement', models.CharField(default='01/01/2000', max_length=15, verbose_name='मिति घोषित')),
            ],
            bases=('master_data.hospital',),
        ),
    ]
