# Generated by Django 3.1.4 on 2021-02-07 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_alter_hospital_body_inheritaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplanactivity',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='allowancetype',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=300, verbose_name='देश'),
        ),
        migrations.AlterField(
            model_name='covidhospital',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.province', verbose_name='प्रदेश'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='जिल्ला'),
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_to_district', to='master_data.province', verbose_name='प्रदेश'),
        ),
        migrations.AlterField(
            model_name='expenseheader',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='governmentbody',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.province', verbose_name='प्रदेश'),
        ),
        migrations.AlterField(
            model_name='importer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.province', verbose_name='प्रदेश'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.province', verbose_name='प्रदेश'),
        ),
        migrations.AlterField(
            model_name='isolationcenter',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.province', verbose_name='प्रदेश'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.province', verbose_name='प्रदेश'),
        ),
        migrations.AlterField(
            model_name='locallevel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_to_district', to='master_data.district', verbose_name='जिल्ला'),
        ),
        migrations.AlterField(
            model_name='locallevel',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='स्थानीय स्तर'),
        ),
        migrations.AlterField(
            model_name='manpower',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='officebearer',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='procurementmethod',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='प्रदेश'),
        ),
        migrations.AlterField(
            model_name='quanrantinecenter',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.province', verbose_name='प्रदेश'),
        ),
        migrations.AlterField(
            model_name='relieftype',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcebudget',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='नाम'),
        ),
    ]
