# Generated by Django 3.1.4 on 2021-02-03 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_alter_hospital_body_inheritaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='governmentbody',
            name='covid_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.covidhospital', verbose_name='अस्पताल'),
        ),
    ]
