# Generated by Django 3.1.4 on 2020-12-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_covidhospital_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentBodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='वर्णन')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.governmentbodytype')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='नाम')),
                ('covid_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.covidhospital', verbose_name='अस्पताल')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.governmentbody')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.governmentbodytype', verbose_name='वर्णन')),
            ],
        ),
    ]
