# Generated by Django 3.1.4 on 2021-02-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_unique_of_master_data_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidhospital',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='नाम'),
        ),
    ]
