# Generated by Django 3.1.4 on 2020-12-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_auto_20201221_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_end',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
