# Generated by Django 3.1.4 on 2021-02-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_auto_20210205_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancetype',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='expenseheader',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='name',
            field=models.CharField(max_length=200, verbose_name='आर्थिक वर्ष'),
        ),
        migrations.AlterField(
            model_name='manpower',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='officebearer',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='procurementmethod',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='sourcebudget',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='नाम'),
        ),
    ]
