# Generated by Django 3.1.4 on 2021-02-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_unique_of_goverment_and_product_model'),
        ('master_data', '0006_auto_20210205_0635'),
    ]

    operations = [
    ]
