# Generated by Django 3.1.4 on 2021-02-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_merge_20210209_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='नाम')),
            ],
        ),
        migrations.CreateModel(
            name='SubHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='नाम')),
            ],
        ),
        migrations.CreateModel(
            name='WorkNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='नाम')),
            ],
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='जिल्ला'),
        ),
        migrations.AlterField(
            model_name='governmentbody',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='governmentbodytype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='वर्णन'),
        ),
        migrations.AlterField(
            model_name='locallevel',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='स्थानीय स्तर'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='नाम'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='प्रदेश'),
        ),
    ]
