# Generated by Django 3.1.4 on 2021-02-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_merge_20210209_0506'),
        ('master_data', '0007_max_length_increase'),
    ]

    operations = [
    ]
