# Generated by Django 3.1.4 on 2021-01-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_actionplanactivity_allowancetype_committee_covidhospitalmanagementchecklistdescription_expenseheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='नाम')),
            ],
        ),
    ]
