# Generated by Django 3.1.4 on 2021-01-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_procurementmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='local_level',
        ),
        migrations.RemoveField(
            model_name='province',
            name='district',
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_to_district', to='master_data.province'),
        ),
        migrations.AddField(
            model_name='locallevel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_to_district', to='master_data.district'),
        ),
    ]
