# Generated by Django 3.1.4 on 2021-01-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_proince_district_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Product', 'Product'), ('Equipment', 'Equipment'), ('ReliefMaterail', 'ReliefMaterial')], max_length=255, verbose_name='प्रकार'),
        ),
    ]
