# Generated by Django 3.1.4 on 2021-02-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_auto_20210211_1335'),
        ('master_data', '0010_alter_locallevel_name'),
    ]

    operations = [
    ]
