# Generated by Django 3.1.4 on 2021-02-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_add_contract_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeskiBibaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(verbose_name='नाम')),
            ],
        ),
    ]
