# Generated by Django 3.1.4 on 2021-02-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_alter_verbose_name_added_in_multiple_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='वर्णन'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='नाम'),
        ),
    ]
