# Generated by Django 3.1.4 on 2021-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_merge_20210217_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='उजुरीको प्रकार')),
            ],
        ),
        migrations.CreateModel(
            name='GrantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='नाम')),
            ],
        ),
        migrations.AlterField(
            model_name='locallevel',
            name='name',
            field=models.CharField(max_length=300, verbose_name='स्थानीय स्तर'),
        ),
    ]
