# Generated by Django 3.1.4 on 2021-02-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_alter_provinceinstitutionmanagement_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='जिल्ला'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='प्रदेश'),
        ),
    ]
