# Generated by Django 3.1.4 on 2021-02-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_add_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenienceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='सुविधाको किसिम')),
            ],
        ),
    ]
