# Generated by Django 3.1.4 on 2021-02-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_constructioncompany_granttype'),
        ('master_data', '0019_add_convenience_type'),
    ]

    operations = [
    ]
