# Generated by Django 3.1.4 on 2021-02-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_merge_20210222_0557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='forms',
            new_name='GrantType',
        ),
    ]
